---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Rubim.
--- DateTime: 23/07/2018 19:21
---
-- HeroLib
local HL = HeroLib;
local Spell = HL.Spell;
local Item = HL.Item;
local MultiSpell = HL.MultiSpell

-- Spells


RubimRH.Spell[3] = {
	Default = Spell(1),
	SteadyShot = Spell(34120),
	SteadyShotz = Spell(25264), --thunder clap
	MultiShotz = Spell(1715), --hamstring
	ArcaneShot = Spell(14287),
	ArcaneShotz = Spell(12328), --sweeping strikes
	AspectoftheHawk = Spell(14320),
	AspectoftheHawkr1 = Spell(27044),
	AspectoftheHawkz = Spell(2458),  --berserker stance
	AspectoftheMonkey = Spell(13163),
	AspectoftheCheetah = Spell(5118),
	AspectofthePack= Spell(13159),
	Drink = Spell(27089),
	MageDrink = Spell(46755),
	Food = Spell(35270),
	AutoShot = Spell(75),
	RaptorStrike = Spell(14266),
	RaptorStrikez = Spell(25236), --execute
	BestialWrath = Spell(37587),
	-- BestialWrath = Spell(37587),
	BestialWrathr1 = Spell(19574),
	BestialWrathz = Spell(2687), --bloodrage
	BloodFury = Spell(20572),
	BloodFuryCancelz = Spell(25241), --slam
	FeignDeath = Spell(5384),
	FeignDeathz = Spell(71), --defensive stance
	RapidFire = Spell(3045),
	RapidFirez = Spell(7386), --sunder
	HuntersMarkz = Spell(5246), --intimidating shout
	AutoAttkz = Spell(20230), --retaliation
	MongooseBite = Spell(14271),
	WingClip = Spell(14268),
	AspectoftheViper = Spell(34074),
	TrackUndead = Spell(19884),
	AspectoftheViperz = Spell(2048), --battle shout
	KillCommand = Spell(34026),
	KillCommandz = Spell(25231), --cleave
	ExplosiveTrap = Spell(14317),
	ExplosiveTrapz = Spell(12975), --last stand
	ExplosiveShot = Spell(60051),
	ExplosiveShotz = Spell(20549), --war stomp
	FreezingTrap = Spell(31933),
	FreezingTrapz = Spell(676), --disarm
	FrostTrap = Spell(13809),
	FrostTrapz = Spell(12292), --death wish
	TrackGiants = Spell(19882),
	Volley = Spell(1510),
	ConcussiveShot = Spell(5116),
	ConcussiveShotz = Spell(12323), --piercing howl
	Intimidation = Spell(24394), 
	Intimidationr1 = Spell(19577), 
	Intimidationz = Spell(1719), --recklessness
	trink1z = Spell(12809), --concussive blow
	trink2z = Spell(100), --charge
	mendpet = Spell(27046),
	mendpetz = Spell(2565), --shieldblock
	FeedPetBuff = Spell(1539),
	FeedPet = Spell(6991),
	FeedPetz = Spell(7165), --battle stance
	Misdirection = Spell(34477),
	ArcaneShotTagz = Spell(1161), --challenging shout
	EatFood = Spell(1160), --demo shout
	SyncMacroz = Spell(14895), --overpower
};

RubimRH.Spell[65] = {
FlashofLight = Spell(19750),
BlessingofFreedom = Spell(1044),
BlessingofProtection = Spell(1022),
BlindingLight = Spell(115750),
HolyPrism = Spell(114165),
Daybreak = Spell(414170),
DivineShield = Spell(642),
HammerofJustice = Spell(853),
HandofDivinity = Spell(414273),
DivineToll = Spell(375576),
BeaconofVirtue = Spell(200025),
TyrsDeliverance = Spell(200652),
AuraMastery = Spell(31821),
Intercession = Spell(391054),
Cleanse = Spell(4987),
};

RubimRH.Spell[263] = {
    autoattack = Spell(274738), -- ancestral call

primalstrike = Spell(73899),
BloodlustPVP = Spell(204361),
bloodlust = Spell(32182),

AncestralSpirit = Spell(2008),
AncestralGuidance = Spell(108281),

EarthbindTotem = Spell(2484),

ChainHeal = Spell(1064),

Thunderstorm = Spell(51490),
EarthernWeapon = Spell(392375),

lustAT = Spell(155145),
lust1 = Spell(57724),
lust2 = Spell(57723),
lust3 = Spell(80354),
lust4 = Spell(95809),
lust5 = Spell(264689),

GhostWolf = Spell(2645),
Purge = Spell(370),
HealingStreamTotem = Spell(5394),


TremorTotem = Spell(8143),

WaterWalking = Spell(546),
Hex = Spell(51514),

Stormbringer = Spell(201846),

CleanseSpirit = Spell(51886),

ChainLightningBuff = Spell(333964),

FeralLunge = Spell(196884),

SpiritWalk = Spell(58875),

LightningLasso = Spell(305483),

VesperTotem = Spell(324386),

DoorofShadows = Spell(300728),
MaelstromWeapon = Spell(344179),
StormKeeper = Spell(320137),
ChainHarvest = Spell(320674),

StoneBulwarkTotem = Spell(108270),


EarthenSpike = Spell(188089),

WinfuryTotemBuff = Spell(327942),

healthstone = Spell(291944),
healingpot = Spell(176108),

Shamanism = Spell(193876),

WindRushTotem = Spell(192077),

Skyfury = Spell(462854),
PoisonCleansingTotem = Spell(383013),

---
---



-- Talents
AncestralSwiftness                    = Spell(443454),
ElementalReverb                       = Spell(443418),
PrimordialCapacity                    = Spell(443448),
  -- Abilities
  TempestAbility                        = Spell(452201),
  TempestOverload                       = Spell(463351),
  -- Talents
  ArcDischarge                          = Spell(455096),
  AwakeningStorms                       = Spell(455129),
  RollingThunder                        = Spell(454026),
  Supercharge                           = Spell(455110),
  Tempest                               = Spell(454009),
  -- Buffs
  ArcDischargeBuff                      = Spell(455097),
  AwakeningStormsBuff                   = Spell(462131),
  TempestBuff                           = Spell(454015),
  AmplificationCore                     = Spell(445029),
  Earthsurge                            = Spell(455590),
  LivelyTotems                          = Spell(445034),
  SurgingTotem                          = Spell(444995),
  TotemicRebound                        = Spell(445025),
-- Racials
AncestralCall                         = Spell(274738),
BagofTricks                           = Spell(312411),
Berserking                            = Spell(26297),
BloodFury                             = Spell(33697),
Fireblood                             = Spell(265221),
-- Abilities
Bloodlust                             = MultiSpell(2825,32182), -- Bloodlust/Heroism
FlameShock                            = MultiSpell(188389,470411),
FlametongueWeapon                     = Spell(318038),
FrostShock                            = Spell(196840),
HealingSurge                          = Spell(8004),
LightningBolt                         = Spell(188196),
LightningShield                       = Spell(192106),
-- Talents
AstralShift                           = Spell(108271),
CapacitorTotem                        = Spell(192058),
ChainLightning                        = Spell(188443),
EarthElemental                        = Spell(198103),
EarthShield                           = Spell(974),
ElementalBlast                        = Spell(117014),
ElementalOrbit                        = Spell(383010),
LavaBurst                             = Spell(51505),
DeeplyRootedElements                  = Spell(378270),
NaturesSwiftness                      = Spell(378081),
PrimordialWave                        = Spell(375982),
SpiritwalkersGrace                    = Spell(79206),
TotemicRecall                         = Spell(108285),
WindShear                             = Spell(57994),
-- Buffs
EarthShieldOtherBuff                  = Spell(974),
EarthShieldSelfBuff                   = Spell(383648),
LightningShieldBuff                   = Spell(192106),
PrimordialWaveBuff                    = Spell(375986),
SpiritwalkersGraceBuff                = Spell(79206),
SplinteredElementsBuff                = Spell(382043),
-- Debuffs
IceStrikePassive = Spell(466467),
FlameShockDebuff                      = Spell(188389),
LightningRodDebuff                    = Spell(197209),
-- Other Class Debuffs
ChaosBrandDebuff                      = Spell(1490),
HuntersMarkDebuff                     = Spell(257284),
-- Trinket Effects
SpymastersReportBuff                  = Spell(451199), -- Stacking buff from before using Spymaster's Web trinket
SpymastersWebBuff                     = Spell(444959), -- Buff from using Spymaster's Web trinket


  -- Abilities
  VoltaicBlazeAbility                   = Spell(470057),
  Windstrike                            = Spell(115356),
  -- Talents
  AlphaWolf                             = Spell(198434),
  Ascendance                            = Spell(114051),
  AshenCatalyst                         = Spell(390370),
  ConvergingStorms                      = Spell(384363),
  CrashLightning                        = Spell(187874),
  CrashingStorms                        = Spell(334308),
  DoomWinds                             = Spell(384352),
  ElementalAssault                      = Spell(210853),
  ElementalSpirits                      = Spell(262624),
  FeralSpirit                           = Spell(51533),
  FireNova                              = Spell(333974),
  FlowingSpirits                        = Spell(469314),
  Hailstorm                             = Spell(334195),
  HotHand                               = Spell(201900),
  IceStrike                             = MultiSpell(342240, 470194),
  LashingFlames                         = Spell(334046),
  LavaLash                              = Spell(60103),
  LegacyoftheFrostWitch                 = Spell(384450),
  MoltenAssault                         = Spell(334033),
  OverflowingMaelstrom                  = Spell(384149),
  RagingMaelstrom                       = Spell(384143),
  StaticAccumulation                    = Spell(384411),
  Stormblast                            = Spell(319930),
  Stormflurry                           = Spell(344357),
  Stormstrike                           = Spell(17364),
  Sundering                             = Spell(197214),
  SwirlingMaelstrom                     = Spell(384359),
  ThorimsInvocation                     = Spell(384444),
  UnrelentingStorms                     = Spell(470490),
  UnrulyWinds                           = Spell(390288),
  VoltaicBlaze                          = Spell(470053),
  WindfuryTotem                         = Spell(8512),
  WindfuryWeapon                        = Spell(33757),
  WitchDoctorsAncestry                  = Spell(384447),
  -- Buffs
  AscendanceBuff                        = Spell(114051),
  AshenCatalystBuff                     = Spell(390371),
  ConvergingStormsBuff                  = Spell(198300),
  CracklingThunderBuff                  = Spell(409834),
  CrashLightningBuff                    = Spell(187878),
  CLCrashLightningBuff                  = Spell(333964),
  DoomWindsBuff                         = Spell(384352),
  EarthenWeaponBuff                     = Spell(392375),
  FeralSpiritBuff                       = Spell(333957),
  GatheringStormsBuff                   = Spell(198300),
  HailstormBuff                         = Spell(334196),
  HotHandBuff                           = Spell(215785),
  IceStrikeBuff                         = Spell(384357),
  LegacyoftheFrostWitchBuff             = Spell(384451),
  MaelstromWeaponBuff                   = Spell(344179),
  StormsurgeBuff                        = Spell(201846),
  WindfuryTotemBuff                     = Spell(327942),
  -- Debuffs
  LashingFlamesDebuff                   = Spell(334168),
  -- Elemental Spirits Buffs
  CracklingSurgeBuff                    = Spell(224127),
  IcyEdgeBuff                           = Spell(224126),
  MoltenWeaponBuff                      = Spell(224125),
  -- Tier 29 Buffs
  MaelstromofElementsBuff               = Spell(394677),
  -- Tier 30 Buffs
  VolcanicStrengthBuff                  = Spell(409833),
}

RubimRH.Spell[253] = {
	BestialWrath = Spell(19574),
	AspectoftheWild = Spell(193530),
	WildSpirits = Spell(328231),
    Intimidation = Spell(19577),
    HuntersMark = Spell(257284),
    ArcaneTorrent = Spell(80483),
	SoulShape = Spell(310143),
    Exhilaration = Spell(109304),
	MultiShot = Spell(2643),
	Flare = Spell(1543),
    MendPet = Spell(136),
	ResonatingArrow = Spell(308491),
    BindingShot = Spell(109248),
    ScatterShot = Spell(213691),
	WailingArrow = Spell(392060),
    TranqShot = Spell(19801),
    CalloftheWild = Spell(359844),
    Beaconz = Spell(69041), --rocket barrage
 }
 
RubimRH.Spell[254] = {
	Volley = Spell(260243),
	DoubleTap = Spell(260402),
	BindingShot = Spell(109248),
	Exhilaration = Spell(109304),
}

 
RubimRH.Spell[255] = {
	BestialWrath = Spell(19574),
	AspectoftheWild = Spell(193530),
	WildSpirits = Spell(328231),
    Intimidation = Spell(19577),
    CalloftheWild = Spell(359844),
    FreezingTrap = Spell(187650),
    FreezingTrapz = Spell(255654), --bullrush
	CoordinatedAssault = Spell(360952),
	SoulShape = Spell(310143),
    Exhilaration = Spell(109304),
	Flare = Spell(1543),
    MendPet = Spell(136),
	ResonatingArrow = Spell(308491),
    FreezingTrap = Spell(187650),
	DeathChakram = Spell(375891),
	DeathChakramz = Spell(260364), --arcane pulse
}
 

RubimRH.Spell[72] = {
    autoattack = Spell(274738), --ancestral call
    lust1 = Spell(57724),
    lust2 = Spell(57723),
    lust3 = Spell(80354),
    lust4 = Spell(95809),
    lust5 = Spell(264689),
    lustAT = Spell(28730), -- arcane turrent
    
    --Fireblood                             = Spell(265221), used for bloodthirst and bloodbath until ggl fixed pixels
    
    -- Racials
    AncestralCall                         = Spell(274738),
    ArcaneTorrent                         = Spell(50613),
    BagofTricks                           = Spell(312411),
    Berserking                            = Spell(26297),
    BloodFury                             = Spell(20572),
    LightsJudgment                        = Spell(255647),
    -- Abilities
    BattleShout                           = Spell(6673),
    BattleStance                          = Spell(386164),
    Charge                                = Spell(100),
    HeroicThrow                           = Spell(57755),
    Pummel                                = Spell(6552),
    Slam                                  = Spell(1464),
    VictoryRush                           = Spell(34428),
    EnragedRegeneration = Spell(184364),
    DefensiveStance                       = Spell(386208),
    -- Talents
    Avatar                                = Spell(107574),
    BerserkerRage                         = Spell(18499),
    BerserkersTorment                     = Spell(390123),
    Bladestorm                            = MultiSpell(227847, 389774),
    BloodandThunder                       = Spell(384277),
    ChampionsSpear                        = Spell(376079),
    DoubleTime                            = Spell(103827),
    CrushingForce                         = Spell(382764),
    FrothingBerserker                     = Spell(215571),
    Hurricane                             = Spell(390563),
    ImmovableObject                       = Spell(394307),
    IntimidatingShout                     = Spell(5246),
    HeroicLeap                            = Spell(6544),
    ImpendingVictory                      = Spell(202168),
    OverwhelmingRage                      = Spell(382767),
    RallyingCry                           = Spell(97462),
    Ravager                               = Spell(228920),
    RumblingEarth                         = Spell(275339),
    Shockwave                             = Spell(46968),
    SonicBoom                             = Spell(390725),
    SpellReflection                       = Spell(23920),
    StormBolt                             = Spell(107570),
    ThunderClap                           = Spell(6343),
    ThunderousRoar                        = Spell(384318),
    TitanicThrow                          = Spell(384090),
    WreckingThrow                         = Spell(384110),
    -- Buffs
    AvatarBuff                            = Spell(107574),
    BattleShoutBuff                       = Spell(6673),
    ChampionsMightBuff                    = Spell(386286),
    HurricaneBuff                         = Spell(390581),
    WarMachineBuff                        = Spell(262232),
    -- Debuffs
    ChampionsMightDebuff                  = Spell(376080),
    MarkofFyralathDebuff                  = Spell(414532),
    ThunderousRoarDebuff                  = Spell(397364),
    -- Pool
    Pool                                  = Spell(999910),
    
    
    
    -- Abilities
    BerserkerStance                       = Spell(386196),
    Bloodbath                             = Spell(335096),
    CrushingBlow                          = Spell(335097),
    Execute                               = MultiSpell(5308, 280735),
    Whirlwind                             = Spell(190411),
    -- Talents
    AngerManagement                       = Spell(152278),
    AshenJuggernaut                       = Spell(392536),
    Bloodthirst                           = Spell(23881),
    DancingBlades                         = Spell(391683),
    ImprovedWhilwind                      = Spell(12950),
    Massacre                              = Spell(206315),
    OdynsFury                             = Spell(385059),
    Onslaught                             = Spell(315720),
    RagingBlow                            = Spell(85288),
    Rampage                               = Spell(184367),
    RecklessAbandon                       = Spell(396749),
    Recklessness                          = Spell(1719),
    Tenderize                             = Spell(388933),
    TitanicRage                           = Spell(394329),
    TitansTorment                         = Spell(390135),
    WrathandFury                          = Spell(392936),
    -- Buffs
    AshenJuggernautBuff                   = Spell(392537),
    BloodcrazeBuff                        = Spell(393951),
    DancingBladesBuff                     = Spell(391688),
    EnrageBuff                            = Spell(184362),
    FuriousBloodthirstBuff                = Spell(423211), -- T31 2pc
    MeatCleaverBuff                       = Spell(85739),
    MercilessAssaultBuff                  = Spell(409983),
    RecklessnessBuff                      = Spell(1719),
    SuddenDeathBuff                       = Spell(280776),
    -- Debuffs
    GushingWoundDebuff                    = Spell(385042),
    OdynsFuryDebuff                       = Spell(385060),
    
    
    
    -- Abilities
    ThunderBlastAbility                   = Spell(435222),
    -- Talents
    CrashingThunder                       = Spell(436707),
    ThunderBlast                          = Spell(435607),
    -- Buffs
    BurstofPowerBuff                      = Spell(437121),
    ThunderBlastBuff                      = Spell(435615),
    
}    
-- General Spells / Potion Icon
RubimRH.Spell[1] = {
    Empty = Spell(1),
    ArcaneTorrent = Spell(80483),
    AncestralCall = Spell(274738),
    Berserking = Spell(26297),
    BloodFury = Spell(20572),
    Fireblood = Spell(265221),
    GiftoftheNaaru = Spell(59547),
    LightsJudgment = Spell(255647),
    UnleashHeartOfAzeroth = Spell(280431),

        -- Potions
    PotionOfProlongedPowerBuff = Spell(229206),
    PotionOfOldWarBuff = Spell(188028),
    LayTorrentBuff = Spell(188030),
    DeadlyGraceBuff = Spell(188027),
    UnbendingPotionBuff = Spell(188029),
    StrenghPotionBuff = Spell(279153),
    StaminaPotionBuff = Spell(279154),
    AgilityPotionBuff = Spell(279152),
    IntPotionBuff = Spell(279151),
}


RubimRH.Spell[102] = {
 
-- Racials
Berserking                            = Spell(26297),
Shadowmeld                            = Spell(58984),
-- Abilities
Barkskin                              = Spell(22812),
BearForm                              = Spell(5487),
CatForm                               = Spell(768),
FerociousBite                         = Spell(22568),
MarkoftheWild                         = Spell(1126),
Moonfire                              = Spell(8921),
Prowl                                 = MultiSpell(5215,102547),
Regrowth                              = Spell(8936),
Shred                                 = Spell(5221),
-- Talents
AstralInfluence                       = Spell(197524),
ConvoketheSpirits                     = Spell(391528),
FluidForm                             = Spell(449193),
FrenziedRegeneration                  = Spell(22842),
HeartoftheWild                        = Spell(319454),
Innervate                             = Spell(29166),
Ironfur                               = Spell(192081),
Maim                                  = Spell(22570),
MightyBash                            = Spell(5211),
MoonkinForm                           = MultiSpell(24858,197625),
NaturesVigil                          = Spell(124974),
PrimalFury                            = Spell(159286),
ProtectorofthePack                    = Spell(378986),
Rake                                  = Spell(1822),
Renewal                               = Spell(108238),
Rip                                   = Spell(1079),
SkullBash                             = Spell(106839),
Starfire                              = Spell(194153),
Starsurge                             = MultiSpell(78674,197626),
Sunfire                               = Spell(93402),
SurvivalInstincts                     = Spell(61336),
ThrashBear                            = Spell(77758),
ThrashCat                             = Spell(106830),
Typhoon                               = Spell(132469),
WildCharge                            = MultiSpell(16979,49376),
-- Buffs
FrenziedRegenerationBuff              = Spell(22842),
HeartoftheWildBuff                    = Spell(319454),
IronfurBuff                           = Spell(192081),
MarkoftheWildBuff                     = Spell(1126),
PoPHealBuff                           = Spell(395336),
SpymastersReportBuff                  = Spell(451199), -- Stacking buff from before using Spymaster's Web trinket
SpymastersWebBuff                     = Spell(444959), -- Buff from using Spymaster's Web trinket
-- Debuffs
MoonfireDebuff                        = Spell(164812),
RakeDebuff                            = Spell(155722),
RipDebuff                             = Spell(1079),
SunfireDebuff                         = Spell(164815),
ThrashBearDebuff                      = Spell(192090),
ThrashCatDebuff                       = Spell(405233),


  -- Talents
  BoundlessMoonlight                    = Spell(424058),
  LunarCalling                          = Spell(429523),
  LunarInsight                          = Spell(429530),
  MoonGuardian                          = Spell(429520),
 -- Talents
 ControloftheDream                     = Spell(434249),
 EarlySpring                           = Spell(428937),
 PoweroftheDream                       = Spell(434220),
 TreantsoftheMoon                      = Spell(428544),
 -- Buffs
 HarmonyoftheGroveBuff                 = Spell(428735),

 -- Abilities
 EclipseLunar                          = Spell(48518),
 EclipseSolar                          = Spell(48517),
 Starfall                              = Spell(191034),
 Wrath                                 = Spell(190984),
 -- Talents
 AetherialKindling                     = Spell(327541),
 AstralCommunion                       = Spell(400636),
 AstralSmolder                         = Spell(394058),
 BalanceofAllThings                    = Spell(394048),
 CelestialAlignment                    = MultiSpell(194223,383410), -- 194223 without Orbital Strike, 383410 with Orbital Strike
 ElunesGuidance                        = Spell(393991),
 ForceofNature                         = Spell(205636),
 FungalGrowth                          = Spell(392999),
 FuryofElune                           = Spell(202770),
 Incarnation                           = MultiSpell(102560,390414), -- 102560 without Orbital Strike, 390414 with Orbital Strike
 IncarnationTalent                     = Spell(394013),
 NaturesBalance                        = Spell(202430),
 NaturesGrace                          = Spell(450347),
 OrbitBreaker                          = Spell(383197),
 OrbitalStrike                         = Spell(390378),
 PowerofGoldrinn                       = Spell(394046),
 PrimordialArcanicPulsar               = Spell(393960),
 RattletheStars                        = Spell(393954),
 Solstice                              = Spell(343647),
 SouloftheForest                       = Spell(114107),
 Starlord                              = Spell(202345),
 Starweaver                            = Spell(393940),
 StellarFlare                          = Spell(202347),
 Swipe                                 = Spell(213764),
 TouchtheCosmos                        = Spell(450356),
 TwinMoons                             = Spell(279620),
 UmbralEmbrace                         = Spell(393760),
 UmbralIntensity                       = Spell(383195),
 WaningTwilight                        = Spell(393956),
 WarriorofElune                        = Spell(202425),
 WhirlingStars                         = Spell(468743),
 WildMushroom                          = Spell(88747),
 WildSurges                            = Spell(406890),
 -- New Moon Phases
 FullMoon                              = Spell(274283),
 HalfMoon                              = Spell(274282),
 NewMoon                               = Spell(274281),
 -- Buffs
 BOATArcaneBuff                        = Spell(394050),
 BOATNatureBuff                        = Spell(394049),
 CABuff                                = Spell(383410),
 DreamstateBuff                        = Spell(450346),
 IncarnationBuff                       = Spell(390414),
 PAPBuff                               = Spell(393961),
 RattledStarsBuff                      = Spell(393955),
 SolsticeBuff                          = Spell(343648),
 StarfallBuff                          = Spell(191034),
 StarlordBuff                          = Spell(279709),
 StarweaversWarp                       = Spell(393942),
 StarweaversWeft                       = Spell(393944),
 TouchtheCosmosBuff                    = Spell(450360),
 UmbralEmbraceBuff                     = Spell(393763),
 WarriorofEluneBuff                    = Spell(202425),
 -- Debuffs
 FungalGrowthDebuff                    = Spell(81281),
 StellarFlareDebuff                    = Spell(202347),
 -- Tier 29 Effects
 GatheringStarstuff                    = Spell(394412),
 -- Legendary Effects
 BOATArcaneLegBuff                     = Spell(339946),
 BOATNatureLegBuff                     = Spell(339943),
 OnethsClearVisionBuff                 = Spell(339797),
 OnethsPerceptionBuff                  = Spell(339800),
 TimewornDreambinderBuff               = Spell(340049),



 -- Racials
 UrsolsVortex = Spell(102793),
 Soothe = Spell(2908),
 StampedingRoar = Spell(106898),
 SolarBeam = Spell(78675),
 Rebirth = Spell(20484),
 IncapacitatingRoar = Spell(99),

Thrash                                = MultiSpell(77758,106830),

ThrashDebuff                          = MultiSpell(106830,192090),
-- Other
Pool                                  = Spell(999910),

autoattack                  = Spell(291944), -- regeneratin

lustAT = Spell(155145),
lust1 = Spell(57724),
lust2 = Spell(57723),
lust3 = Spell(80354),
lust4 = Spell(95809),
lust5 = Spell(264689),


}

-- Spells
RubimRH.Spell[66] = {
 -- 42422
Repentance = Spell(20066),
TurnEvil = Spell(10326),
SanctificationBuff                    = Spell(424616), -- T31, 2pc
SanctificationEmpowerBuff             = Spell(424622), -- T31, 2pc
BulwarkofRighteousFury                = Spell(386653),

BulwarkofRighteousFuryBuff            = Spell(386652),
Sentinel = Spell(389539),
BlessingofFreedom           = Spell(1044),
BlindingLight               = Spell(115750),
-- SenseUndead                 = Spell(5502),
SacredWeapon                         = Spell(432472),
SacredWeaponBuff                     = Spell(432502),
CleanseToxins               = Spell(213644),
autoattack                  = Spell(291944), -- regeneratin
BlessedAssuranceBuff                 = Spell(433019),
tempestofthelightbringer    = Spell(383396),

DivineSteedBuff             = Spell(221883),
BlessingofProtection        = Spell(1022),
Forbearance                 = Spell(25771),
-- Racials
AncestralCall               = Spell(274738),
ArcanePulse                 = Spell(260364),
ArcaneTorrent               = Spell(155145),
BagofTricks                 = Spell(312411),
LightsGuidance = Spell(427445),
LightsDeliverance                    = Spell(425518),

Berserking                  = Spell(26297),
BloodFury                   = Spell(20572),
-- Fireblood                             = Spell(265221),
GiftoftheNaaru              = Spell(59542),
-- Abilities
ShiningLightFreeBuff                  = Spell(327510),
RighteousProtector                    = Spell(204074),

InmostLight                           = Spell(405757),
MomentofGloryBuff                     = Spell(327193),
FinalStand                  = Spell(204077),
Consecration                = Spell(26573),
CrusaderStrike              = Spell(35395),


Redoubt                               = Spell(280373),
RedoubtBuff                           = Spell(280375),

DivineShield                = Spell(642),
DivineSteed                 = Spell(190784),
FlashofLight                = Spell(19750),
HammerofJustice             = Spell(853),
HandofReckoning             = Spell(62124),
Rebuke                      = Spell(96231),
ShieldoftheRighteous        = Spell(53600),
WordofGlory                 = Spell(85673),
-- Talents
AvengingWrath               = Spell(31884),
HolyBulwark = Spell(432459),
HammerofWrath               = Spell(24275),
HolyAvenger                 = Spell(105809),
HammerofLight = Spell(427453),
HoL = Spell(427445),
HolyAvengerBuff             = Spell(105809),
LayonHands                  = Spell(633),

-- Covenants (Shadowlands)
BlessingofFreedomfocus = Spell(145067),-- turn evil

-- DivineTollCov                         = Spell(304971),
DoorofShadows               = Spell(300728),
Fleshcraft                  = Spell(324631),
Soulshape                   = Spell(310143),
SummonSteward               = Spell(324739),
VanquishersHammer           = Spell(328204),
VanquishersHammerBuff       = Spell(328204),
-- Soulbinds/Conduits (Shadowlands)
Expurgation                 = Spell(339371),
PustuleEruption             = Spell(351094),
VengefulShock               = Spell(340006),
VengefulShockDebuff         = Spell(340007),
VolatileSolvent             = Spell(323074),
VolatileSolventHumanBuff    = Spell(323491),
-- Auras
ConcentrationAura           = Spell(317920),
CrusaderAura                = Spell(32223),
DevotionAura                = Spell(465),
OfDuskandDawn                         = Spell(409441),

RetributionAura             = Spell(183435),
-- Buffs
BlessingofSpellWarding = Spell(204018),
Intercession                = Spell(391054),
intercession                = Spell(105809),
trinket                     = Spell(59547), -- gift of narru
CleanseToxinsFocus = Spell(20594), --stone form
WordofGloryFocus = Spell(215652), --shield of virtue
BlessingofProtectionFocus = Spell(204018),-- blessing of spellwarding
BlessingofSacrifice = Spell(6940),
LayonHandsFocus = Spell(172321),--seraphim
BastionofLightBuff                    = Spell(378974),
BlessingofDawnBuff                    = Spell(385127),
BlessingofDuskBuff                    = Spell(385126),
AvengingWrathBuff           = Spell(31884),
ConsecrationBuff            = Spell(188370),
DivinePurposeBuff           = Spell(223819),
ScarsofFraternalStrifeBuff4 = Spell(368638),
ShieldoftheRighteousBuff    = Spell(132403),
TemptationBuff              = Spell(234143),
-- Debuffs
CruelGarroteDebuff          = Spell(230011),
-- Legendary Effects
DivineResonanceBuff         = Spell(355455),
FinalVerdictBuff            = Spell(337228),
-- Pool

Entangled = Spell(408556),
-- Pool                                  = Spell(999910),
Pool = Spell(397799),

deepchill = Spell(391634),
HSicon = Spell(255647),--lights judgment
lust1    = Spell(57724),
lust2    = Spell(57723),
lust3    = Spell(80354),
lust4    = Spell(95809),
lust5    = Spell(264689),
lustAT   = Spell(20549), -- war stomp
EmpoweredConsecration = Spell(424622),
EyeofTyr = Spell(387174),
FrostShock = Spell(385963),
IcyBindings = Spell(377488),

ArdentDefender         = Spell(31850),
AvengersShield         = Spell(31935),
GuardianofAncientKings = Spell(86659),

HammeroftheRighteous   = Spell(53595),
Judgment               = Spell(275779),
JudgmentDebuff         = Spell(197277),
ShiningLightBuff           = Spell(327510),
ShiningLightBuffStack           = Spell(182104),
-- Talents
BlessedHammer          = Spell(204019),
CrusadersJudgment      = Spell(204023),
MomentofGlory          = Spell(327193),
SanctifiedWrath        = Spell(171648),
DivineToll             = Spell(375576),



BastionofLight = Spell(378974),


}




-- Spells
RubimRH.Spell[250] = {
          -- Abilities
          DeathandDecay                         = Spell(43265),
          DeathCoil                             = Spell(47541),
          -- Talents
          AbominationLimb                       = Spell(383269),
          AntiMagicBarrier                      = Spell(205727),
          AntiMagicShell                        = Spell(48707),
          AntiMagicZone                         = Spell(51052),
          Asphyxiate                            = Spell(221562),
          Assimilation                          = Spell(374383),
          ChainsofIce                           = Spell(45524),
          CleavingStrikes                       = Spell(316916),
          DeathStrike                           = Spell(49998),
          EmpowerRuneWeapon                     = Spell(47568),
          IceboundFortitude                     = Spell(48792),
          IcyTalons                             = Spell(194878),
          RaiseDead                             = Spell(46585),
          RunicAttenuation                      = Spell(207104),
          SacrificialPact                       = Spell(327574),
          SoulReaper                            = Spell(343294),
          UnholyGround                          = Spell(374265),
          UnyieldingWill                        = Spell(457574),
          -- Buffs
          AbominationLimbBuff                   = Spell(383269),
          DeathandDecayBuff                     = Spell(188290),
          DeathStrikeBuff                       = Spell(101568),
          EmpowerRuneWeaponBuff                 = Spell(47568),
          IcyTalonsBuff                         = Spell(194879),
          RuneofHysteriaBuff                    = Spell(326918),
          UnholyStrengthBuff                    = Spell(53365),
          -- Debuffs
          BloodPlagueDebuff                     = Spell(55078),
          FrostFeverDebuff                      = Spell(55095),
          MarkofFyralathDebuff                  = Spell(414532),
          SoulReaperDebuff                      = Spell(343294),
          VirulentPlagueDebuff                  = Spell(191587),
          -- Racials
          AncestralCall                         = Spell(274738),
          ArcanePulse                           = Spell(260364),
          ArcaneTorrent                         = Spell(50613),
          BagofTricks                           = Spell(312411),
          Berserking                            = Spell(26297),
          BloodFury                             = Spell(20572),
          Fireblood                             = Spell(265221),
          LightsJudgment                        = Spell(255647),
          -- Interrupts
          MindFreeze                            = Spell(47528),
          -- Custom
        -- Talents
        DarkTalons                            = Spell(436687),
        Exterminate                           = Spell(441378),
        ReapersMark                           = Spell(439843),
        -- Buffs
        ExterminateBuff                       = Spell(441416),
        PainfulDeathBuff                      = Spell(447954),
        -- Debuffs
        ReapersMarkDebuff                     = Spell(434765),
         -- Talents
         AFeastofSouls                         = Spell(444072),
         ApocalypseNow                         = Spell(444040),
         -- Buffs
         AFeastofSoulsBuff                     = Spell(440861),
         MograinesMightBuff                    = Spell(444505),
         -- Debuffs
         TrollbaneSlowDebuff                   = Spell(444834),
        
         lust1    = Spell(57724),
         lust2    = Spell(57723),
         lust3    = Spell(80354),
         lust4    = Spell(95809),
         lust5    = Spell(264689),
         lustAT   = Spell(155145), -- arcane torrent
         autoattack = Spell(59752), -- will to survive (human racial)
        
         DeathGrip = Spell(49576),
         DeathCharge = Spell(444347),
         Lichborne = Spell(20549), -- war stomp
         RaiseAlly = Spell(61999),
        -- Abilities
        VampiricStrikeAction                  = Spell(433895),
        -- Talents
        GiftoftheSanlayn                      = Spell(434152),
        VampiricStrike                        = Spell(433901),
        -- Buffs
        EssenceoftheBloodQueenBuff            = Spell(433925),
        GiftoftheSanlaynBuff                  = Spell(434153),
        InflictionofSorrowBuff                = Spell(460049),
        VampiricStrikeBuff                    = Spell(433899),
        -- Debuffs
        InciteTerrorDebuff                    = Spell(458478),
        -- Abilities
          -- Talents
          BloodBoil                             = Spell(50842),
          BloodTap                              = Spell(221699),
          Blooddrinker                          = Spell(206931),
          Bonestorm                             = Spell(194844),
          Coagulopathy                          = Spell(391477),
          Consumption                           = Spell(274156),
          DancingRuneWeapon                     = Spell(49028),
          DeathsCaress                          = Spell(195292),
          GorefiendsGrasp                       = Spell(108199),
          HeartStrike                           = Spell(206930),
          Heartbreaker                          = Spell(221536),
          InsatiableBlade                       = Spell(377637),
          Marrowrend                            = Spell(195182),
          RapidDecomposition                    = Spell(194662),
          RelishinBlood                         = Spell(317610),
          RuneTap                               = Spell(194679),
          SanguineGround                        = Spell(391458),
          ShatteringBone                        = Spell(377640),
          TighteningGrasp                       = Spell(206970),
          Tombstone                             = Spell(219809),
          VampiricBlood                         = Spell(55233),
          -- Buffs
          BoneShieldBuff                        = Spell(195181),
          CoagulopathyBuff                      = Spell(391481),
          ConsumptionBuff                       = Spell(274156),
          CrimsonScourgeBuff                    = Spell(81141),
          DancingRuneWeaponBuff                 = Spell(81256),
          HemostasisBuff                        = Spell(273947),
          IceboundFortitudeBuff                 = Spell(48792),
          RuneTapBuff                           = Spell(194679),
          VampiricBloodBuff                     = Spell(55233),
          VampiricStrengthBuff                  = Spell(408356), -- Tier 30 4pc
   
   
   }
   




RubimRH.Spell[268] = {
    -- Spells
		Vivify = Spell(116670),

    ArcaneTorrent = Spell(50613),
    Berserking = Spell(26297),
    BlackoutCombo = Spell(196736),
    BlackoutComboBuff = Spell(228563),
    BlackoutStrike = Spell(205523),
    BlackOxBrew = Spell(115399),
    BloodFury = Spell(20572),
    BreathOfFire = Spell(115181),
    BreathofFireDotDebuff = Spell(123725),
    Brews = Spell(115308),
    ChiBurst = Spell(123986),
    ChiWave = Spell(115098),
    DampenHarm = Spell(122278),
    DampenHarmBuff = Spell(122278),
    ExpelHarm = Spell(115072),
    ExplodingKeg = Spell(214326),
    FortifyingBrew = Spell(115203),
    FortifyingBrewBuff = Spell(115203),
    InvokeNiuzaotheBlackOx = Spell(132578),
    IronskinBrew = Spell(115308),
    IronskinBrewBuff = Spell(215479),
    KegSmash = Spell(121253),
    LightBrewing = Spell(196721),
    PotentKick = Spell(213047),
    PurifyingBrew = Spell(119582),
    RushingJadeWind = Spell(116847),
    TigerPalm = Spell(100780),
    HeavyStagger = Spell(124273),
    ModerateStagger = Spell(124274),
    LightStagger = Spell(124275),
    SpearHandStrike = Spell(116705),
    ModerateStagger = Spell(124274),
    HeavyStagger = Spell(124273),
    HealingElixir = Spell(122281),
    BlackOxStatue = Spell(115315),
    Guard = Spell(202162),
    LegSweep = Spell(119381),
	QuackingPalm = Spell(107079),
	Paralysis = Spell(115078),
	Vivify = Spell(116670),
	
	--8.2 Essences
  UnleashHeartOfAzeroth = Spell(280431),
  BloodOfTheEnemy       = Spell(297108),
  BloodOfTheEnemy2      = Spell(298273),
  BloodOfTheEnemy3      = Spell(298277),
  ConcentratedFlame     = Spell(295373),
  ConcentratedFlame2    = Spell(299349),
  ConcentratedFlame3    = Spell(299353),
  GuardianOfAzeroth     = Spell(295840),
  GuardianOfAzeroth2    = Spell(299355),
  GuardianOfAzeroth3    = Spell(299358),
  FocusedAzeriteBeam    = Spell(295258),
  FocusedAzeriteBeam2   = Spell(299336),
  FocusedAzeriteBeam3   = Spell(299338),
  PurifyingBlast        = Spell(295337),
  PurifyingBlast2       = Spell(299345),
  PurifyingBlast3       = Spell(299347),
  TheUnboundForce       = Spell(298452),
  TheUnboundForce2      = Spell(299376),
  TheUnboundForce3      = Spell(299378),
  RippleInSpace         = Spell(302731),
  RippleInSpace2        = Spell(302982),
  RippleInSpace3        = Spell(302983),
  WorldveinResonance    = Spell(295186),
  WorldveinResonance2   = Spell(298628),
  WorldveinResonance3   = Spell(299334),
  MemoryOfLucidDreams   = Spell(298357),
  MemoryOfLucidDreams2  = Spell(299372),
  MemoryOfLucidDreams3  = Spell(299374),
}


--Retribution
RubimRH.Spell[70] = {
BlessingofProtection = Spell(1022),
BlessingofFreedom = Spell(1044),
HammerofJustice = Spell(853),
hammerofjustice = Spell(20594),
DivineShield = Spell(642),
ArcaneTorrent = Spell(155145),
WakeofAshes = Spell(255937),
HandofHindrance = Spell(183218),
FlashofLight = Spell(19750),
KingsB = Spell(203538),
Kings = Spell(265221),
WisdomB = Spell(203539),
Wisdom = Spell(255647),
RecklessForce = Spell(298445),
trinket = Spell(20549),
HoJ = Spell(20594),
HS = Spell(291944),
FAB = Spell(299338),
FABg = Spell(84963),
BladeofJustice = Spell(184575),
Consecration = Spell(205228),
CrusaderStrike = Spell(35395),
DivineJudgment = Spell(271580),
DivineHammer = Spell(198034),
DivinePurpose = Spell(223817),
DivinePurposeBuff = Spell(223819),
DivineStorm = Spell(53385),
ExecutionSentence = Spell(343527),
GreaterJudgment = Spell(218718),
HolyWrath = Spell(210220),
Judgment = Spell(20271),
JudgmentDeBuff = Spell(197277),
JusticarsVengeance = Spell(215661),
TemplarsVerdict = Spell(85256),
TheFiresofJustice = Spell(203316),
TheFiresofJusticeBuff = Spell(209785),
Zeal = Spell(217020),
FinalVerdict = Spell(198038),
ShieldofVengeance = Spell(184662),
Forbearance = Spell(25771),
AvengingWrath = Spell(31884),
Crusade = Spell(231895),
Inquisition = Spell(84963),
DivineJudgement = Spell(271580),
HammerofWrath = Spell(24275),
RighteousVerdict = Spell(267610),
EmpyreanPowerAzerite = Spell(286390),
EmpyreanPowerBuffAzerite = Spell(286393),
DivineStormBuffAzerite = Spell(278523),
DivineRight = Spell(277678),
SelfLessHealerBuff = Spell(114250),
LayonHands = Spell(633),
WordofGlory = Spell(210191),
Rebuke = Spell(96231),
DivineSteed = Spell(190784),
LiadrinsFuryUnleashed = Spell(208408),
ScarletInquisitorsExpurgation = Spell(248289),
WhisperoftheNathrezim = Spell(207635),
HammerOfReckoning = Spell(247675),
HammerOfReckoningBuff = Spell(247677),
HandOfHidrance = Spell(183218),
CondensedLifeForce = Spell(299358),
UnleashHeartOfAzeroth = Spell(280431),
BloodOfTheEnemy = Spell(297108),
BloodOfTheEnemy2 = Spell(298273),
BloodOfTheEnemy3 = Spell(298277),
ConcentratedFlame = Spell(295373),
ConcentratedFlame2 = Spell(299349),
ConcentratedFlame3 = Spell(299353),
GuardianOfAzeroth = Spell(295840),
GuardianOfAzeroth2 = Spell(299355),
GuardianOfAzeroth3 = Spell(299358),
FocusedAzeriteBeam = Spell(295258),
FocusedAzeriteBeam2 = Spell(299336),
FocusedAzeriteBeam3 = Spell(299338),
PurifyingBlast = Spell(295337),
PurifyingBlast2 = Spell(299345),
PurifyingBlast3 = Spell(299347),
TheUnboundForce = Spell(298452),
TheUnboundForce2 = Spell(299376),
TheUnboundForce3 = Spell(299378),
RippleInSpace = Spell(302731),
RippleInSpace2 = Spell(302982),
RippleInSpace3 = Spell(302983),
WorldveinResonance = Spell(295186),
WorldveinResonance2 = Spell(298628),
WorldveinResonance3 = Spell(299334),
MemoryOfLucidDreams = Spell(298357),
MemoryOfLucidDreams2 = Spell(299372),
MemoryOfLucidDreams3 = Spell(299374),
}

RubimRH.Spell[251] = {
 -- Abilities
 DeathandDecay                         = Spell(43265),
 DeathCoil                             = Spell(47541),
 -- Talents
 AbominationLimb                       = Spell(383269),
 AntiMagicBarrier                      = Spell(205727),
 AntiMagicShell                        = Spell(48707),
 AntiMagicZone                         = Spell(51052),
 Asphyxiate                            = Spell(221562),
 Assimilation                          = Spell(374383),
 ChainsofIce                           = Spell(45524),
 CleavingStrikes                       = Spell(316916),
 DeathStrike                           = Spell(49998),
 EmpowerRuneWeapon                     = Spell(47568),
 IceboundFortitude                     = Spell(48792),
 IcyTalons                             = Spell(194878),
 RaiseDead                             = Spell(46585),
 RunicAttenuation                      = Spell(207104),
 SacrificialPact                       = Spell(327574),
 SoulReaper                            = Spell(343294),
 UnholyGround                          = Spell(374265),
 UnyieldingWill                        = Spell(457574),
 -- Buffs
 AbominationLimbBuff                   = Spell(383269),
 DeathandDecayBuff                     = Spell(188290),
 DeathStrikeBuff                       = Spell(101568),
 EmpowerRuneWeaponBuff                 = Spell(47568),
 IcyTalonsBuff                         = Spell(194879),
 RuneofHysteriaBuff                    = Spell(326918),
 UnholyStrengthBuff                    = Spell(53365),
 -- Debuffs
 BloodPlagueDebuff                     = Spell(55078),
 FrostFeverDebuff                      = Spell(55095),
 MarkofFyralathDebuff                  = Spell(414532),
 SoulReaperDebuff                      = Spell(343294),
 VirulentPlagueDebuff                  = Spell(191587),
 -- Racials
 AncestralCall                         = Spell(274738),
 ArcanePulse                           = Spell(260364),
 ArcaneTorrent                         = Spell(50613),
 BagofTricks                           = Spell(312411),
 Berserking                            = Spell(26297),
 BloodFury                             = Spell(20572),
 Fireblood                             = Spell(265221),
 LightsJudgment                        = Spell(255647),
 -- Interrupts
 MindFreeze                            = Spell(47528),
 -- Custom
 Lichborne = Spell(20549), -- war stomp
RaiseAlly = Spell(61999),
-- Talents
DarkTalons                            = Spell(436687),
Exterminate                           = Spell(441378),
ReapersMark                           = Spell(439843),
-- Buffs
ExterminateBuff                       = Spell(441416),
PainfulDeathBuff                      = Spell(447954),
-- Debuffs
ReapersMarkDebuff                     = Spell(434765),
DeathCharge = Spell(444347),
-- Talents
AFeastofSouls                         = Spell(444072),
ApocalypseNow                         = Spell(444040),
-- Buffs
AFeastofSoulsBuff                     = Spell(440861),
MograinesMightBuff                    = Spell(444505),
-- Debuffs
TrollbaneSlowDebuff                   = Spell(444834),

-- Abilities
VampiricStrikeAction                  = Spell(433895),
-- Talents
GiftoftheSanlayn                      = Spell(434152),
VampiricStrike                        = Spell(433901),
-- Buffs
EssenceoftheBloodQueenBuff            = Spell(433925),
GiftoftheSanlaynBuff                  = Spell(434153),
InflictionofSorrowBuff                = Spell(460049),
VampiricStrikeBuff                    = Spell(433899),
-- Debuffs
InciteTerrorDebuff                    = Spell(458478),
-- Abilities
FrostStrike                           = Spell(49143),
HowlingBlast                          = Spell(49184),
-- Talents
ArcticAssault                         = Spell(456230),
Avalanche                             = Spell(207142),
BitingCold                            = Spell(377056),
Bonegrinder                           = Spell(377098),
BreathofSindragosa                    = Spell(152279),
ChillStreak                           = Spell(305392),
ColdHeart                             = Spell(281208),
EnduringStrength                      = Spell(377190),
FrigidExecutioner                     = Spell(377073),
DeathGrip = Spell(49576),
Frostscythe                           = Spell(207230),
FrostwyrmsFury                        = Spell(279302),
GatheringStorm                        = Spell(194912),
GlacialAdvance                        = Spell(194913),
HornofWinter                          = Spell(57330),
Icebreaker                            = Spell(392950),
Icecap                                = Spell(207126),
Obliterate                            = Spell(49020),
Obliteration                          = Spell(281238),
PillarofFrost                         = Spell(51271),
RageoftheFrozenChampion               = Spell(377076),
RemorselessWinter                     = Spell(196770),
ShatteredFrost                        = Spell(455993),
ShatteringBlade                       = Spell(207057),
SmotheringOffense                     = Spell(435005),
TheLongWinter                         = Spell(456240),
UnleashedFrenzy                       = Spell(376905),
-- Buffs
BonegrinderFrostBuff                  = Spell(377103),
ColdHeartBuff                         = Spell(281209),
KillingMachineBuff                    = Spell(51124),
PillarofFrostBuff                     = Spell(51271),
RimeBuff                              = Spell(59052),
UnleashedFrenzyBuff                   = Spell(376907),
-- Debuffs
RazoriceDebuff                        = Spell(51714),

lust1    = Spell(57724),
lust2    = Spell(57723),
lust3    = Spell(80354),
lust4    = Spell(95809),
lust5    = Spell(264689),
lustAT   = Spell(155145), -- arcane torrent
autoattack = Spell(59752), -- will to survive (human racial)
  }

RubimRH.Spell[73] = {
    -- Racials
	RallyingCry = Spell(97462),
    BattleShout = Spell(6673),
    ArcaneTorrent = Spell(69179),
    Berserking = Spell(26297),
	Reflect = Spell(23920),
	ShieldBlockBuff = Spell(132404),
    Shadowmeld = Spell(58984),
    -- Abilities
	CracklingThunder = Spell(203201),
    Ravager = Spell(22401),
    BattleCry = Spell(1719),
	StormBolt = Spell(107570),
    BerserkerRage = Spell(18499),
    Charge = Spell(100),
    DemoralizingShout = Spell(1160),
    Devastate = Spell(20243),
    FuriousSlash = Spell(100130),
    HeroicLeap = Spell(6544),
    HeroicThrow = Spell(57755),
    Revenge = Spell(6572),
    RevengeBuff = Spell(5302),
    ShieldSlam = Spell(23922),
    ThunderClap = Spell(6343),
    VictoryRush = Spell(34428),
    Victorious = Spell(32216),
	DragonRoar = Spell (23260),
    -- Talents
	BoomingVoice = Spell(202743),
	ShieldBash = Spell(35178),
	Bolster = Spell(280001),
    ImpendingVictory = Spell(202168),
    ImpendingVictoryProc = Spell(32216),
    Shockwave = Spell(46968),
    Vengeance = Spell(202572),
    VengeanceIP = Spell(202574),
    VengeanceRV = Spell(202573),
	Execute = Spell(163201), 
	UnstoppableForce = Spell(275336),
    -- Artifact
    NeltharionsFury = Spell(203524),
    -- Defensive
    IgnorePain = Spell(190456),
    LastStand = Spell(12975),
    Pummel = Spell(6552),
    ShieldBlock = Spell(2565),
    ShieldBlockB = Spell(132404),
    Avatar = Spell(107574),
	ShieldWall = Spell(871),
	FM = Spell(20594),
    Condemn = Spell(317349),
    trinket = Spell(155145),
    IntimidatingShout = Spell(5246),
}

RubimRH.Spell[260] = {
    Shiv = Spell(5938),

BladeRush = Spell(271877),

stopcasting = Spell(291944), -- regeneratin

 
CripplingPoison = Spell(3408),
cripplingpoison = Spell(260364), -- arcane pulse
InstantPoison = Spell(315584),
instantpoison = Spell(274738), --ancestral call
 

lust1 = Spell(57724),
lust2 = Spell(57723),
lust3 = Spell(80354),
lust4 = Spell(95809),
lust5 = Spell(264689),
--enrage
UndyingRage = Spell(333227),

		  --8.2 Essences
  CondensedLifeForce = Spell(299358),
  UnleashHeartOfAzeroth = Spell(280431),
  BloodOfTheEnemy       = Spell(297108),
  BloodOfTheEnemy2      = Spell(298273),
  BloodOfTheEnemy3      = Spell(298277),
  ConcentratedFlame     = Spell(295373),
  ConcentratedFlame2    = Spell(299349),
  ConcentratedFlame3    = Spell(299353),
  GuardianOfAzeroth     = Spell(295840),
  GuardianOfAzeroth2    = Spell(299355),
  GuardianOfAzeroth3    = Spell(299358),
  FocusedAzeriteBeam    = Spell(295258),
  FocusedAzeriteBeam2   = Spell(299336),
  FocusedAzeriteBeam3   = Spell(299338),
  PurifyingBlast        = Spell(295337),
  PurifyingBlast2       = Spell(299345),
  PurifyingBlast3       = Spell(299347),
  TheUnboundForce       = Spell(298452),
  TheUnboundForce2      = Spell(299376),
  TheUnboundForce3      = Spell(299378),
  RippleInSpace         = Spell(302731),
  RippleInSpace2        = Spell(302982),
  RippleInSpace3        = Spell(302983),
  WorldveinResonance    = Spell(295186),
  WorldveinResonance2   = Spell(298628),
  WorldveinResonance3   = Spell(299334),
  MemoryOfLucidDreams   = Spell(298357),
  MemoryOfLucidDreams2  = Spell(299372),
  MemoryOfLucidDreams3  = Spell(299374),
  trink2 = Spell(59547), -- gift of naaru
	  ConcentratedFlamedebuff     = Spell(295368),
	FocusedAzeriteBeam = Spell(295258),
	KYWAY = Spell(288979),
	
    AceUpYourSleeve = Spell(278676),
    Deadshot = Spell(272935),
    Berserking = Spell(26297),

    Darkflight = Spell(68992),

    -- Debuff List
	Distract = Spell(1725),
	distract = Spell(20572), --shadowmeld
lustAT = Spell(155145),

bagoftricks = Spell(312411),
    	--Mount
    WaterStrider = Spell(118089),
    BugMount = Spell(243795),
razorcoral = Spell(303568),
ConductiveInk = Spell(302565),
    -- Abilities
    AdrenalineRush = Spell(13750),
    Ambush = Spell(8676),
    Detection = Spell(56814), --opener
	KidneyShot = Spell(408),
    BetweentheEyes = Spell(315341),
    BladeFlurry = Spell(13877),
    BladeFlurry2 = Spell(103828), -- Icon: Prot. Warrior Warbringer
    DeeperStratagem = Spell(193531),
    DeviousStratagem = Spell(394321),
    Opportunity = Spell(195627),
    PistolShot = Spell(185763),
    RolltheBones = Spell(315508),
    Dispatch = Spell(2098),
    SinisterStrike = Spell(193315),
	Dreadblades = Spell(343142),
    Stealth = Spell(1784),
    Vanish = Spell(1856),
    VanishBuff = Spell(11327),
    Shivv = Spell(248744),
    Riposte = Spell(199754),
    WilloftheForsaken = Spell(7744),
    CloakofShadows = Spell(31224),
    -- Talents
	trink = Spell(265221),
    Alacrity = Spell(193539),
    AlacrityBuff = Spell(193538),
    Anticipation = Spell(114015),
    CannonballBarrage = Spell(185767),
    DeathfromAbove = Spell(152150),
    DeeperStratagem = Spell(193531),
    DirtyTricks = Spell(108216),
    GhostlyStrike = Spell(196937),
    KillingSpree = Spell(51690),
    MarkedforDeath = Spell(137619),
    QuickDraw = Spell(196938),
    Tricks = Spell(57934),
    ToTT = Spell(58984),
	sliceanddice = Spell(198529), -- plunder armor
    SliceandDice = Spell(315496),
    Vigor = Spell(14983),
    -- Artifact
	Exhaustion = Spell(57723),
	Blind = Spell(2094),
    Blunderbuss = Spell(202895),
    CurseoftheDreadblades = Spell(202665),
    HiddenBlade = Spell(202754),
    LoadedDice = Spell(256171),
    DeadshotBuff = Spell(272940),
	AceUpYourSleeve = Spell(278676),
	SnakeEyes = Spell(275846),
	SnakeEyesBuff = Spell(275863),
    -- Defensive
	DS = Spell(642),
	CheapShot = Spell(1833),
	Dismantle= Spell(207777),
    CrimsonVial = Spell(185311),
    Feint = Spell(1966),
    -- Utility
    Gouge = Spell(1776),
    Kick = Spell(1766),
    Sprint = Spell(2983),
    -- Roll the Bones
    Broadside = Spell(193356),
    BuriedTreasure = Spell(199600),
    GrandMelee = Spell(193358),
    SkullandCrossbones = Spell(199603),
	GCBoon = Spell(20572),
    RuthlessPrecision = Spell(193357),
    TrueBearing = Spell(193359),


}

RubimRH.Spell[269] = {
RingofPeace = Spell(116844),
LegSweep = Spell(119381),
FlyingSerpentKick = Spell(101545),
Paralysis = Spell(115078),
CracklingJadeLightning = Spell(117952),
}

RubimRH.Spell[270] = {
Vivify = Spell(116670),
FaelineStomp = Spell(388193),
LegSweep = Spell(119381),
LifeCocoon = Spell(116849),
ChiJi = Spell(325197),
RingofPeace = Spell(116844),
Revival = Spell(115310),
Detox = Spell(115450),
}
----SHAMMY
--ELE
RubimRH.Spell[262] = {
    autoattack                  = Spell(291944), -- regeneratin
 
 FirstAscendant                        = Spell(462440),

 StormFrenzyBuff                       = Spell(462725),

 -- Tier Bonuses
 MaelstromSurgeBuff                    = Spell(457727), -- TWWS1 4pc
  ElementalReverb                       = Spell(443418),


  LightningShield                       = Spell(192106),


  -- Other Class Debuffs
  ChaosBrandDebuff                      = Spell(1490),
  HuntersMarkDebuff                     = Spell(257284),
  -- Trinket Effects
  SpymastersReportBuff                  = Spell(451199), -- Stacking buff from before using Spymaster's Web trinket
  SpymastersWebBuff                     = Spell(444959), -- Buff from using Spymaster's Web trinket
  AmplificationCore                     = Spell(445029),
  Earthsurge                            = Spell(455590),
  LivelyTotems                          = Spell(445034),
  SurgingTotem                          = Spell(444995),
  TotemicRebound                        = Spell(445025),

AncestralCall                         = Spell(274738),
BagofTricks                           = Spell(312411),
Berserking                            = Spell(26297),
EarthbindTotem = Spell(2484),
Purge = Spell(370),

BloodFury                             = Spell(33697),
Fireblood                             = Spell(265221),
-- Abilities
Skyfury = Spell(462854),
Bloodlust                             = MultiSpell(2825,32182), -- Bloodlust/Heroism
WindRushTotem = Spell(192077),
FlameShock                            = Spell(470411),
FlametongueWeapon                     = Spell(318038),
FrostShock                            = Spell(196840),
AncestralGuidance = Spell(108281),
HealingSurge                          = Spell(8004),
LightningBolt                         = Spell(188196),
ThunderstrikeWard = Spell(462757), 
-- Talents
AstralShift                           = Spell(108271),
CapacitorTotem                        = Spell(192058),
ChainLightning                        = Spell(188443),
EarthElemental                        = Spell(198103),
EarthShield                           = Spell(974),
ElementalBlast                        = Spell(117014),
ElementalOrbit                        = Spell(383010),
LavaBurst                             = Spell(51505),
DeeplyRootedElements                  = Spell(378270),
NaturesSwiftness                      = Spell(378081),
PrimordialWave                        = Spell(375982),
SpiritwalkersGrace                    = Spell(79206),
TotemicRecall                         = Spell(108285),
WindShear                             = Spell(57994),
-- Buffs
EarthShieldOtherBuff                  = Spell(974),
EarthShieldSelfBuff                   = Spell(383648),
LightningShieldBuff                   = Spell(192106),
PrimordialWaveBuff                    = Spell(375986),
SpiritwalkersGraceBuff                = Spell(79206),
SplinteredElementsBuff                = Spell(382043),
-- Debuffs
FlameShockDebuff                      = Spell(188389),
-- Misc
Pool                                  = Spell(999910),
StoneBulwarkTotem = Spell(108270), 
GustofWind = Spell(192063),

Thunderstorm = Spell(51490),
lustAT = Spell(155145),
lust1 = Spell(57724),
lust2 = Spell(57723),
lust3 = Spell(80354),
lust4 = Spell(95809),
lust5 = Spell(264689),
CleanseSpirit = Spell(51886),
GhostWolf = Spell(2645),
-- Abilities
EarthShock                            = Spell(8042),
Earthquake                            = MultiSpell(61882, 462620),
FireElemental                         = Spell(198067),
-- Talents
Ascendance                            = Spell(114050),
EchoChamber                           = Spell(382032),
-- Talents
ArcDischarge                          = Spell(455096),
AwakeningStorms                       = Spell(455129),
RollingThunder                        = Spell(454026),
Supercharge                           = Spell(455110),
-- Buffs
ArcDischargeBuff                      = Spell(455097),
AwakeningStormsBuff                   = Spell(462131),
TempestBuff                           = Spell(454015),
EchooftheElements                     = Spell(333919),
EchoesofGreatSundering                = Spell(384087),
ElectrifiedShocks                     = Spell(382086),
EyeoftheStorm                         = Spell(381708),
FlowofPower                           = Spell(385923),
FluxMelting                           = Spell(381776),
FusionofElements                      = Spell(462840),
Icefury                               = Spell(210714),
ImprovedFlametongueWeapon             = Spell(382027),
LavaBeam                              = Spell(114074),
LightningRod                          = Spell(210689),
LiquidMagmaTotem                      = Spell(192222),
MagmaChamber                          = Spell(381932),
MasteroftheElements                   = Spell(16166),
MountainsWillFall                     = Spell(381726),
PoweroftheMaelstrom                   = Spell(191861),
PrimalElementalist                    = Spell(117013),
SearingFlames                         = Spell(381782),
SkybreakersFieryDemise                = Spell(378310),
SplinteredElements                    = Spell(382042),
StormElemental                        = Spell(192249),
Stormkeeper                           = Spell(191634),
SurgeofPower                          = Spell(262303),
SwellingMaelstrom                     = Spell(381707),
-- ThunderstrikeWard                     = Spell(462757),
-- Buffs
AscendanceBuff                        = Spell(114050),
EchoesofGreatSunderingBuff            = Spell(384088),
FluxMeltingBuff                       = Spell(381777),
PoisonCleansingTotem = Spell(383013),
FusionofElementsFire                  = Spell(462843),
FusionofElementsNature                = Spell(462841),
IcefuryBuff                           = Spell(210714),
LavaSurgeBuff                         = Spell(77762),
MagmaChamberBuff                      = Spell(381933),
MasteroftheElementsBuff               = Spell(260734),
PoweroftheMaelstromBuff               = Spell(191877),
StormkeeperBuff                       = Spell(191634),
SurgeofPowerBuff                      = Spell(285514),
-- Debuffs
ElectrifiedShocksDebuff               = Spell(382089),
LightningRodDebuff                    = Spell(197209),

-- Abilities
TempestAbility                        = Spell(452201),
TempestOverload                       = Spell(463351),
-- Talents
Tempest                               = Spell(454009),
TremorTotem = Spell(8143),

-- Talents
AncestralSwiftness                    = Spell(443454),
PrimordialCapacity                    = Spell(443448),
}

----ROGUE
--ASS

--SUB
RubimRH.Spell[261] = {
    -- Racials
    brez = Spell(69070), --rocket jump
	Rupture = Spell(1943),
    ArcanePulse = Spell(260364),
    ArcaneTorrent = Spell(50613),
    Berserking = Spell(26297),
    BloodFury = Spell(20572),
    Shadowmeld = Spell(58984),
    -- Abilities
    Backstab = Spell(53),
	ShurikenTornado = Spell(277925),
    Eviscerate = Spell(196819),
    Nightblade = Spell(195452),
    ShadowBlades = Spell(121471),
    ShurikenComboBuff = Spell(245640),
    ShadowDance = Spell(185313),
    ShadowDanceBuff = Spell(185422),
    Shadowstrike = Spell(185438),
    ShurikenStorm = Spell(197835),
    ShurikenToss = Spell(114014),
    Stealth = Spell(1784),
    Stealth2 = Spell(115191), -- w/ Subterfuge Talent
    SymbolsofDeath = Spell(212283),
    Vanish = Spell(1856),
    VanishBuff = Spell(11327),
    VanishBuff2 = Spell(115193), -- w/ Subterfuge Talent
    -- Talents
    Alacrity = Spell(193539),
    DarkShadow = Spell(245687),
    DeeperStratagem = Spell(193531),
    EnvelopingShadows = Spell(238104),
    FindWeaknessDebuff = Spell(91021),
    Gloomblade = Spell(200758),
    MarkedforDeath = Spell(137619),
    MasterofShadows = Spell(196976),
    Nightstalker = Spell(14062),
    SecretTechnique = Spell(280719),
    ShadowFocus = Spell(108209),
    ShurikenTornado = Spell(277925),
    Subterfuge = Spell(108208),
    Vigor = Spell(14983),
    -- Azerite Traits
    SharpenedBladesBuff = Spell(272916),
    -- Defensive
    CrimsonVial = Spell(185311),
    Feint = Spell(1966),
    -- Utility
    Blind = Spell(2094),
    CheapShot = Spell(1833),
    Kick = Spell(1766),
    KidneyShot = Spell(408),
    Sprint = Spell(2983),
    -- Misc
}

----HUNTER
--BeastMastery

----DRUID
-- Feral
RubimRH.Spell[103] = {
    Regrowth = Spell(8936),
	Soothe = Spell(2908),
    Hibernate = Spell(2637),
    RemoveCorruption = Spell(2782),
	WildCharge = Spell(49376),
	Typhoon = Spell(132469),
	Typhoonz = Spell(20549), --war stomp
	Vortex = Spell(102793),
    Convoke = Spell(391528),
    Bloodtalons = Spell(155672),
    StampedingRoar = Spell(77764),
    CatForm = Spell(768),
	IncapacitatingRoar = Spell(99),
    BearForm = Spell(5487),
    Prowl = Spell(5215),
    Rebirth = Spell(20484),
    IncarnationBuff = Spell(102543),
    JungleStalkerBuff = Spell(252071),
	Maim = Spell(22570),
    Berserk = Spell(106951),
    TigersFury = Spell(5217),
    TigersFuryBuff = Spell(5217),
    EntanglingRoots = Spell(339),
    Berserking = Spell(26297),
    FeralFrenzy = Spell(274837),
    Incarnation = Spell(102543),
    BerserkBuff = Spell(106951),
    Shadowmeld = Spell(58984),
    Rake = Spell(1822),
    RakeDebuff = Spell(155722),
    BloodtalonsBuff = Spell(145152),
    CatFormBuff = Spell(768),
    ProwlBuff = Spell(5215),
    ShadowmeldBuff = Spell(58984),
    FerociousBite = Spell(22568),
    RipDebuff = Spell(1079),
    Sabertooth = Spell(202031),
    PredatorySwiftnessBuff = Spell(69369),
    ApexPredatorBuff = Spell(252752),
    MomentofClarity = Spell(236068),
    SavageRoar = Spell(52610),
    SavageRoarBuff = Spell(52610),
    Rip = Spell(1079),
    FerociousBiteMaxEnergy = Spell(22568),
    BrutalSlash = Spell(202028),
    ThrashCat = Spell(106830),
    ThrashCatDebuff = Spell(106830),
    MoonfireCat = Spell(155625),
    MoonfireCatDebuff = Spell(155625),
    ClearcastingBuff = Spell(135700),
    SwipeCat = Spell(106785),
    Shred = Spell(5221),
    LunarInspiration = Spell(155580),
	Dash = Spell(1850),
	FrenziedRegeneration = Spell(22842),
}
-- Guardian
RubimRH.Spell[104] = {
  -- Racials
  Berserking                            = Spell(26297),
  Shadowmeld                            = Spell(58984),
  -- Abilities
 
  Barkskin                              = Spell(22812),
  BearForm                              = Spell(5487),
  CatForm                               = Spell(768),
  FerociousBite                         = Spell(22568),
  MarkoftheWild                         = Spell(1126),
  Moonfire                              = Spell(8921),
  Prowl                                 = MultiSpell(5215,102547),
  Regrowth                              = Spell(8936),
  Shred                                 = Spell(5221),
  -- Talents
  AstralInfluence                       = Spell(197524),
  ConvoketheSpirits                     = Spell(391528),
  FluidForm                             = Spell(449193),
  FrenziedRegeneration                  = Spell(22842),
  HeartoftheWild                        = Spell(319454),
  Innervate                             = Spell(29166),
  Ironfur                               = Spell(192081),
  Maim                                  = Spell(22570),
  MightyBash                            = Spell(5211),
  MoonkinForm                           = MultiSpell(24858,197625),
  NaturesVigil                          = Spell(124974),
  PrimalFury                            = Spell(159286),
  ProtectorofthePack                    = Spell(378986),
  Rake                                  = Spell(1822),
  Renewal                               = Spell(108238),
  Rip                                   = Spell(1079),
  SkullBash                             = Spell(106839),
  Starfire                              = Spell(194153),
  Starsurge                             = MultiSpell(78674,197626),
  Sunfire                               = Spell(93402),
  SurvivalInstincts                     = Spell(61336),
  ThrashBear                            = Spell(77758),
  ThrashCat                             = Spell(106830),
  Typhoon                               = Spell(132469),
  WildCharge                            = MultiSpell(16979,49376),
  -- Buffs
  FrenziedRegenerationBuff              = Spell(22842),
  HeartoftheWildBuff                    = Spell(319454),
  IronfurBuff                           = Spell(192081),
  MarkoftheWildBuff                     = Spell(1126),
  PoPHealBuff                           = Spell(395336),
  SpymastersReportBuff                  = Spell(451199), -- Stacking buff from before using Spymaster's Web trinket
  SpymastersWebBuff                     = Spell(444959), -- Buff from using Spymaster's Web trinket
  -- Debuffs
  MoonfireDebuff                        = Spell(164812),
  RakeDebuff                            = Spell(155722),
  RipDebuff                             = Spell(1079),
  SunfireDebuff                         = Spell(164815),
  ThrashBearDebuff                      = Spell(192090),
  ThrashCatDebuff                       = Spell(405233),
  -- Other
  Pool                                  = Spell(999910),
  
    -- Talents
    BoundlessMoonlight                    = Spell(424058),
    LunarCalling                          = Spell(429523),
    LunarInsight                          = Spell(429530),
    MoonGuardian                          = Spell(429520),
  -- Abilities
  Mangle                                = Spell(33917),
  -- Talents
  Berserk                               = Spell(50334),
  BristlingFur                          = Spell(155835),
  FlashingClaws                         = Spell(393427),
  FuryofNature                          = Spell(370695),
  Incarnation                           = Spell(102558),
  LunarBeam                             = Spell(204066),
  Maul                                  = Spell(6807),
  Pulverize                             = Spell(80313),
  RageoftheSleeper                      = Spell(200851),
  Raze                                  = Spell(400254),
  ReinforcedFur                         = Spell(393618),
  SouloftheForest                       = Spell(158477),
  Swipe                                 = Spell(213771),
  ThornsofIron                          = Spell(400222),
  -- Buffs
  DreamofCenariusBuff                   = Spell(372152),
  GalacticGuardianBuff                  = Spell(213708),
  GoreBuff                              = Spell(93622),
  ToothandClawBuff                      = Spell(135286),
  ViciousCycleMaulBuff                  = Spell(372015),
  ViciousCycleMangleBuff                = Spell(372019),
 Growl = Spell(6795),
   -- Abilities
   RavageAbilityBear                     = Spell(441605),
   RavageAbilityCat                      = Spell(441591),
   -- Talents
   FountofStrength                       = Spell(441675),
   Ravage                                = Spell(441583),
   WildpowerSurge                        = Spell(441691),
   RemoveCorruption = Spell(2782),
   -- Buffs
   FelinePotentialBuff                   = Spell(441701),
   RavageBuffFeral                       = Spell(441585),
   RavageBuffGuardian                    = Spell(441602),
 autoattack                  = Spell(291944), -- regeneratin
 IncapacitatingRoar = Spell(99),
 lustAT = Spell(155145),
 lust1 = Spell(57724),
 lust2 = Spell(57723),
 lust3 = Spell(80354),
 lust4 = Spell(95809),
 lust5 = Spell(264689),
 StampedingRoar = Spell(106898),

}


----DEATH KNIGHT
--FROST

----DEMONHUNTER
RubimRH.Spell[581] = {
    -- Baseline
    SigilofSilence = Spell(207682),
}
-- Vengeance


-- Havoc
RubimRH.Spell[577] = {
    EyeBeam = Spell(198013),
	ChaosNova = Spell(179057),
	Metamorphosis = Spell(191427),
	FelRush = Spell(195072),
	VengefulRetreat = Spell(198793),
	FelEruption = Spell(211881),
	Darkness = Spell(196718),
	GlaiveTempest = Spell(342817),
    Blur = Spell(198589),
    ConsumeMagic = Spell(278326),
	Imprison = Spell(217832),
    SpectralSight = Spell(188501),
    ThrowGlaive = Spell(185123),
    SinfulBrand = Spell(317009),
	theHunt = Spell(323639),
}

-- Affliction
RubimRH.Spell[265] = {
    -- Baseline
    DemonicGateway = Spell(111771),
    CreateSoulwell = Spell(29893),
    EnslaveDemon = Spell(1098),
    UnendingResolve = Spell(104773),
    Soulstone = Spell(20707),
    RitualOfSummoning = Spell(698),
    CommandDemon = Spell(119898),
    SummonFelhunter = Spell(691),
    Banish = Spell(710),
    SummonSuccubus = Spell(712),
    UnendingBreath = Spell(5697),
    HealthFunnel = Spell(755),
    SummonVoidwalker = Spell(697),
    CreateHealthstone = Spell(6201),
    Fear = Spell(5782),
    SummonImp = Spell(688),
    -- Specialization
    PotentAfflictions = Spell(77215),
    Shadowfury = Spell(30283),
    SummonDarkglare = Spell(205180),
    Agony = Spell(980),
    SeedOfCorruption = Spell(27243),
    UnstableAffliction = Spell(30108),
    UnstableAfflictionDot = Spell(233490),
    DrainLife = Spell(234153),
    Corruption = Spell(172),
    CorruptionPerma = Spell(146739),
    ShadowBolt = Spell(232670),
    -- Talents
    CreepingDeath = Spell(264000),
    Deathbolt = Spell(264106),
    DarkSoulMisery = Spell(113860),
    SoulConduit = Spell(215941),
    GrimoireOfSacrifice = Spell(108503),
    Haunt = Spell(48181),
    PhantomSingularity = Spell(205179),
    SowTheSeeds = Spell(196226),
    VileTaint = Spell(278350),
    AbsoluteCorruption = Spell(196103),
    WritheInAgony = Spell(196102),
    DrainSoul = Spell(198590),
    Nightfall = Spell(108558),
    SiphonLife = Spell(63106)
}

RubimRH.Spell[266] = {
  -- Racials
  Berserking            = Spell(26297),
  BloodFury             = Spell(20572),
  Fireblood             = Spell(265221),
  -- Abilities
  DrainLife             = Spell(234153),
  SummonDemonicTyrant   = Spell(265187),
  SummonImp             = Spell(688),
  SummonFelguard        = Spell(30146),
  HandOfGuldan          = Spell(105174),
  ShadowBolt            = Spell(686),
  Demonbolt             = Spell(264178),
  CallDreadStalkers     = Spell(104316),
  Fear                  = Spell(5782),
  Implosion             = Spell(196277),
  Shadowfury            = Spell(30283),

  -- Pet abilities
  CauterizeMaster         = Spell(119905),--imp
  Suffering               = Spell(119907),--voidwalker
  Whiplash                = Spell(119909),--Bitch
  FelStormFake            = Spell(29893),-- HAck == CreateSoulwell
  FelStorm                = Spell(89751),--FelGuard
  PetStun                 = Spell(119914),
  SpellLock               = Spell(119898),

  -- Talents
  Dreadlash               = Spell(264078),
  DemonicStrength         = Spell(267171),
  BilescourgeBombers      = Spell(267211),

  DemonicCalling          = Spell(205145),
  PowerSiphon             = Spell(264130),
  Doom                    = Spell(265412),
  DoomDebuff              = Spell(265412),

  DemonSkin               = Spell(219272),
  BurningRush             = Spell(111400),
  DarkPact                = Spell(108416),

  FromTheShadows          = Spell(267170),
  SoulStrike              = Spell(264057),
  SummonVilefiend         = Spell(264119),

  Darkfury                = Spell(264874),
  MortalCoil              = Spell(6789),
  DemonicCircle           = Spell(268358),

  InnerDemons             = Spell(267216),
  SoulConduit             = Spell(215941),
  GrimoireFelguard        = Spell(111898),

  SacrificedSouls         = Spell(267214),
  DemonicConsumption      = Spell(267215),
  NetherPortal            = Spell(267217),
  NetherPortalBuff        = Spell(267218),

  -- Defensive
  UnendingResolve         = Spell(104773),

  -- Azerite
  ForbiddenKnowledge      = Spell(279666),
  BalefulInvocation       = Spell(287059),
  ExplosivePotentialBuff  = Spell(275398),
  ExplosivePotential      = Spell(275395),

  -- Utility
  TargetEnemy             = Spell(153911),--doesnt work
  CreateHealthstone       = Spell(6201),--using this instead to target enemy
  
  -- Misc
  DemonicCallingBuff      = Spell(205146),
  DemonicCoreBuff         = Spell(264173),
  DemonicPowerBuff        = Spell(265273)
}