---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Rubim.
--- DateTime: 23/07/2018 19:21
---
-- HeroLib
local HL = HeroLib;
local Spell = HL.Spell;
local Item = HL.Item;
-- Spells


RubimRH.Spell[3] = {
	Default = Spell(1),
	SteadyShot = Spell(34120),
	SteadyShotz = Spell(25264), --thunder clap
	MultiShotz = Spell(1715), --hamstring
	ArcaneShot = Spell(14287),
	ArcaneShotz = Spell(12328), --sweeping strikes
	AspectoftheHawk = Spell(14320),
	AspectoftheHawkr1 = Spell(27044),
	AspectoftheHawkz = Spell(2458),  --berserker stance
	AspectoftheMonkey = Spell(13163),
	AspectoftheCheetah = Spell(5118),
	AspectofthePack= Spell(13159),
	Drink = Spell(27089),
	MageDrink = Spell(46755),
	Food = Spell(35270),
	AutoShot = Spell(75),
	RaptorStrike = Spell(14266),
	RaptorStrikez = Spell(25236), --execute
	BestialWrath = Spell(37587),
	-- BestialWrath = Spell(37587),
	BestialWrathr1 = Spell(19574),
	BestialWrathz = Spell(2687), --bloodrage
	BloodFury = Spell(20572),
	BloodFuryCancelz = Spell(25241), --slam
	FeignDeath = Spell(5384),
	FeignDeathz = Spell(71), --defensive stance
	RapidFire = Spell(3045),
	RapidFirez = Spell(7386), --sunder
	HuntersMarkz = Spell(5246), --intimidating shout
	AutoAttkz = Spell(20230), --retaliation
	MongooseBite = Spell(14271),
	WingClip = Spell(14268),
	AspectoftheViper = Spell(34074),
	TrackUndead = Spell(19884),
	AspectoftheViperz = Spell(2048), --battle shout
	KillCommand = Spell(34026),
	KillCommandz = Spell(25231), --cleave
	ExplosiveTrap = Spell(14317),
	ExplosiveTrapz = Spell(12975), --last stand
	ExplosiveShot = Spell(60051),
	ExplosiveShotz = Spell(20549), --war stomp
	FreezingTrap = Spell(31933),
	FreezingTrapz = Spell(676), --disarm
	FrostTrap = Spell(13809),
	FrostTrapz = Spell(12292), --death wish
	TrackGiants = Spell(19882),
	Volley = Spell(1510),
	ConcussiveShot = Spell(5116),
	ConcussiveShotz = Spell(12323), --piercing howl
	Intimidation = Spell(24394), 
	Intimidationr1 = Spell(19577), 
	Intimidationz = Spell(1719), --recklessness
	trink1z = Spell(12809), --concussive blow
	trink2z = Spell(100), --charge
	mendpet = Spell(27046),
	mendpetz = Spell(2565), --shieldblock
	FeedPetBuff = Spell(1539),
	FeedPet = Spell(6991),
	FeedPetz = Spell(7165), --battle stance
	Misdirection = Spell(34477),
	ArcaneShotTagz = Spell(1161), --challenging shout
	EatFood = Spell(1160), --demo shout
	SyncMacroz = Spell(14895), --overpower
};

RubimRH.Spell[65] = {
FlashofLight = Spell(19750),
BlessingofFreedom = Spell(1044),
BlessingofProtection = Spell(1022),
BlindingLight = Spell(115750),
HolyPrism = Spell(114165),
Daybreak = Spell(414170),
DivineShield = Spell(642),
HammerofJustice = Spell(853),
HandofDivinity = Spell(414273),
DivineToll = Spell(375576),
BeaconofVirtue = Spell(200025),
TyrsDeliverance = Spell(200652),
AuraMastery = Spell(31821),
Intercession = Spell(391054),
Cleanse = Spell(4987),
};

RubimRH.Spell[263] = {
Hailstorm = Spell(334195),
AncestralGuidance = Spell(108281),
Windstrike = Spell(115356),	
AncestralSpirit = Spell(2008),
LightningLasso = Spell(305483),
Thunderstorm = Spell(51490),
ChainLightning = Spell(188443),
AstralShift = Spell(108271),
PrimordialWave = Spell(375982),
DoomWinds = Spell(384352),
EarthbindTotem = Spell(2484),
EarthElemental = Spell(198103),
CapacitorTotem = Spell(192058),
FlameShock = Spell(188389),
ChainHeal = Spell(1064),
FlametongueWeapon = Spell(318038),
FrostShock = Spell(196840),
LightningShield = Spell(192106),
GhostWolf = Spell(2645),
Purge = Spell(370),
HealingStreamTotem = Spell(5394),
TremorTotem = Spell(8143),
HealingSurge = Spell(8004),
WaterWalking = Spell(546),
Hex = Spell(51514),
WindShear = Spell(57994),
LightningBolt = Spell(188196),
CleanseSpirit = Spell(51886),
CrashLightning = Spell(187874),
EarthShield = Spell(974),
FeralLunge = Spell(196884),
FeralSpirit = Spell(51533),
Sundering = Spell(197214),
LavaLash = Spell(60103),
SpiritWalk = Spell(58875),
StormStrike = Spell(17364),
WindfuryTotem = Spell(8512),
WindfuryWeapon = Spell(33757),
Ascendance = Spell(114051),
FireNova = Spell(333974),
LashingFlames = Spell(334046),
-- DoomWinds = Spell(),
-- PrimalLavaActuators = Spell(),
PrimordialWave = Spell(326059), 
VesperTotem = Spell(324386),
DoorofShadows = Spell(300728),
MaelstromWeapon = Spell(344179),
StormKeeper = Spell(320137),
ChainHarvest = Spell(320674),
-- FaeTransfusion = Spell(),
ElementalBlast = Spell(22353),
Sundering = Spell(197214),
IceStrike = Spell(342240),
EarthenSpike = Spell(188089),
CrashingStorm = Spell(192246),
WinfuryTotemBuff = Spell(327942),
HotHand = Spell(201900),
Steward = Spell(324739),
lust1 = Spell(57724),
lust2 = Spell(57723),
lust3 = Spell(80354),
lust4 = Spell(95809),
lust5 = Spell(264689),
Berserking = Spell(26297),
healthstone = Spell(291944),
healingpot = Spell(176108),
PrimordialWaveBuff = Spell(327164),
Bloodlust = Spell(204361),
}

RubimRH.Spell[253] = {
	BestialWrath = Spell(19574),
	AspectoftheWild = Spell(193530),
	WildSpirits = Spell(328231),
    Intimidation = Spell(19577),
    HuntersMark = Spell(257284),
    ArcaneTorrent = Spell(80483),
	SoulShape = Spell(310143),
    Exhilaration = Spell(109304),
	MultiShot = Spell(2643),
	Flare = Spell(1543),
    MendPet = Spell(136),
	ResonatingArrow = Spell(308491),
    BindingShot = Spell(109248),
    ScatterShot = Spell(213691),
	WailingArrow = Spell(392060),
    TranqShot = Spell(19801),
    CalloftheWild = Spell(359844),
    Beaconz = Spell(69041), --rocket barrage
 }
 
RubimRH.Spell[254] = {
	Volley = Spell(260243),
	DoubleTap = Spell(260402),
	BindingShot = Spell(109248),
	Exhilaration = Spell(109304),
}

 
RubimRH.Spell[255] = {
	BestialWrath = Spell(19574),
	AspectoftheWild = Spell(193530),
	WildSpirits = Spell(328231),
    Intimidation = Spell(19577),
    CalloftheWild = Spell(359844),
    FreezingTrap = Spell(187650),
    FreezingTrapz = Spell(255654), --bullrush
	CoordinatedAssault = Spell(360952),
	SoulShape = Spell(310143),
    Exhilaration = Spell(109304),
	Flare = Spell(1543),
    MendPet = Spell(136),
	ResonatingArrow = Spell(308491),
    FreezingTrap = Spell(187650),
	DeathChakram = Spell(375891),
	DeathChakramz = Spell(260364), --arcane pulse
}
 

RubimRH.Spell[72] = {
	
	 ColdSteelHotBlood = Spell(288080), -- update
	
	
	IntimidatingShout = Spell(5246),
    ArcaneTorrent = Spell(80483),
    AncestralCall = Spell(274738),
    Berserking = Spell(26297),
    BloodFury = Spell(20572),
    Fireblood = Spell(265221),
    GiftoftheNaaru = Spell(59547),
    LightsJudgment = Spell(255647),
    -- Abilities
    BattleShout = Spell(6673),
    BerserkerRage = Spell(18499),
    Bloodthirst = Spell(23881),
    Charge = Spell(100),
    Execute = Spell(5308),
    HeroicLeap = Spell(6544),
    HeroicThrow = Spell(57755),
	
	CrushingBlow = Spell(335097),
	BloodBath = Spell(335096),
    RagingBlow = Spell(85288),
    Rampage = Spell(184367),
    Recklessness = Spell(1719),
    VictoryRush = Spell(34428),
    Whirlwind = Spell(190411),
    WhirlwindPassive = Spell(12950),
    WhirlwindBuff = Spell(85739),
    EnragedRegeneration = Spell(184364),
    Enrage = Spell(184362),
    -- Talents
    WarMachine = Spell(262231),
    EndlessRage = Spell(202296),
    FreshMeat = Spell(215568),
    DoubleTime = Spell(103827),
    ImpendingVictory = Spell(202168),
    StormBolt = Spell(107570),
    InnerRage = Spell(215573),
    FuriousSlash = Spell(100130),
    FuriousSlashBuff = Spell(202539),
    Carnage = Spell(202922),
    Massacre = Spell(206315),
    
    MeatCleaver = Spell(280392),
    MeatCleaverBuff = Spell(280392),
    DragonRoar = Spell(118000),
    Bladestorm = Spell(46924),
    RecklessAbandon = Spell(202751),
    AngerManagement = Spell(152278),
    SiegeBreaker = Spell(280772),
    SiegeBreakerTalent = Spell(16037),
    SiegeBreakerDebuff = Spell(280773),
    SuddenDeath = Spell(280721),
    SuddenDeathBuff = Spell(280776),
    SuddenDeathBuffLeg = Spell(225947),
    Victorious = Spell(32216),
    VictoryRush = Spell(34428),
    -- Defensive
    RallyingCry = Spell(97462),
    -- Utility
    Pummel = Spell(6552),
    PiercingHowl = Spell(12323),
    -- Legendaries
    FujiedasFury = Spell(207776),
    StoneHeart = Spell(225947),
    -- Misc
    UmbralMoonglaives = Spell(242553),
    SpellReflection = Spell(216890),
    -- Azerite
    AzeriteColdSteelHotBlood = Spell(288080),
	
			  --8.2 Essences
 }
-- General Spells / Potion Icon
RubimRH.Spell[1] = {
    Empty = Spell(1),
    ArcaneTorrent = Spell(80483),
    AncestralCall = Spell(274738),
    Berserking = Spell(26297),
    BloodFury = Spell(20572),
    Fireblood = Spell(265221),
    GiftoftheNaaru = Spell(59547),
    LightsJudgment = Spell(255647),
    UnleashHeartOfAzeroth = Spell(280431),

        -- Potions
    PotionOfProlongedPowerBuff = Spell(229206),
    PotionOfOldWarBuff = Spell(188028),
    LayTorrentBuff = Spell(188030),
    DeadlyGraceBuff = Spell(188027),
    UnbendingPotionBuff = Spell(188029),
    StrenghPotionBuff = Spell(279153),
    StaminaPotionBuff = Spell(279154),
    AgilityPotionBuff = Spell(279152),
    IntPotionBuff = Spell(279151),
}


RubimRH.Spell[102] = {

Quake = Spell(240447),

MassEntanglement = Spell(102359),
forceofnature = Spell(205636),
Vortex = Spell(102793),
vortex = Spell(58984),
FrenziedRegeneration = Spell(22842),
Thrash = Spell(20549), --warstomp
ThrashDebuff = Spell(192090),
Mangle = Spell(33917),
Ironfur = Spell(192081),
StarfallBuff = Spell(191034),
TravelForm = Spell(783),
BearForm = Spell(5487),
CatForm = Spell(768),
Rebirth = Spell(20484),
EntanglingRoots = Spell(339),
Cyclone = Spell(33786),
cyclone = Spell(287712),
swiftmend = Spell(18562),
typhoon = Spell(209749),
Rejuvenation = Spell(774),
WildGrowth = Spell(48438),
RemoveCorruption = Spell(2782),
Dash = Spell(1850),
StampedingRoar = Spell(106898),
    MoonkinForm                           = Spell(24858),
    Wrath                                 = Spell(190984),
    FuryofElune                           = Spell(202770),
    CelestialAlignmentBuff                = Spell(194223),
    IncarnationBuff                       = Spell(102560),
    CelestialAlignment                    = Spell(194223),
    Incarnation                           = Spell(102560),
    ForceofNature                         = Spell(205636),
    Sunfire                               = Spell(93402),
    SunfireDebuff                         = Spell(164815),
    Moonfire                              = Spell(8921),
    Regrowth                              = Spell(8936),
    MoonfireDebuff                        = Spell(164812),
    StellarFlare                          = Spell(202347),
	StellarFlareDebuff                    = Spell(202347),
    Starfire                              = Spell(194153),
    LunarEmpowermentBuff                  = Spell(164547),
    SolarEmpowermentBuff                  = Spell(164545),
    Starsurge                             = Spell(78674),
    OnethsIntuitionBuff                   = Spell(209406),
    Starfall                              = Spell(191034),
    StarlordBuff                          = Spell(279709),
    NewMoon                               = Spell(274281),
    HalfMoon                              = Spell(274282),
    FullMoon                              = Spell(274283),
    WarriorofEluneBuff                    = Spell(202425),
    BloodFury                             = Spell(20572),
    Berserking                            = Spell(26297),
    ArcaneTorrent                         = Spell(50613),
    LightsJudgment                        = Spell(255647),
    WarriorofElune                        = Spell(202425),
    SunblazeBuff                          = Spell(274399),
    OwlkinFrenzyBuff                      = Spell(157228),
    SolarBeam                             = Spell(78675),
	LivelySpirit                          = Spell(279642),
	LivelySpiritBuff                      = Spell(279646),
	StreakingStars                        = Spell(272871),
	ShootingStars                         = Spell(202342),
    NaturesBalance                        = Spell(202430),
	Barkskin                              = Spell(22812),
	Soothe                                = Spell(2908),
	Innervate                             = Spell(29166),
	Renewal                               = Spell(108238),
    Typhoon                               = Spell(132469),
	MightyBash                            = Spell(5211),
	ArcanicPulsarBuff                     = Spell(287790),
    ArcanicPulsar                         = Spell(287773),
	StarlordBuff                          = Spell(279709),
    Starlord                              = Spell(202345),
	-- 8.2 Essences
    SolarBeam                             = Spell(78675),
	UnleashHeartOfAzeroth                 = Spell(280431),
    BloodOfTheEnemy                       = Spell(297108),
    BloodOfTheEnemy2                      = Spell(298273),
    BloodOfTheEnemy3                      = Spell(298277),
    MemoryOfLucidDreams                   = Spell(298357),
    MemoryOfLucidDreams2                  = Spell(299372),
    MemoryOfLucidDreams3                  = Spell(299374),
    PurifyingBlast                        = Spell(295337),
    PurifyingBlast2                       = Spell(299345),
    PurifyingBlast3                       = Spell(299347),
    RippleInSpace                         = Spell(302731),
    RippleInSpace2                        = Spell(302982),
    RippleInSpace3                        = Spell(302983),
    ConcentratedFlame                     = Spell(295373),
    ConcentratedFlame2                    = Spell(299349),
    ConcentratedFlame3                    = Spell(299353),
    TheUnboundForce                       = Spell(298452),
    TheUnboundForce2                      = Spell(299376),
    TheUnboundForce3                      = Spell(299378),
    RecklessForce                         = Spell(302932),
    WorldveinResonance                    = Spell(295186),
    WorldveinResonance2                   = Spell(298628),
    WorldveinResonance3                   = Spell(299334),
    FocusedAzeriteBeam                    = Spell(295258),
    FocusedAzeriteBeam2                   = Spell(299336),
    FocusedAzeriteBeam3                   = Spell(299338),
    GuardianOfAzeroth                     = Spell(295840),
    GuardianOfAzeroth2                    = Spell(299355),
    GuardianOfAzeroth3                    = Spell(299358),
    Thorns                                = Spell(236696),
    TwinMoons                             = Spell(279620),
	ShootingStars                         = Spell(202342),
    NaturesBalance                        = Spell(202430),
    Barkskin                              = Spell(22812),
    Renewal                               = Spell(108238),
    SolarBeam                             = Spell(78675),
    ShiverVenomDebuff                     = Spell(301624),
    CyclotronicBlast                      = Spell(167672),
    AzsharasFontofPowerBuff               = Spell(296962),
StellarDrift = Spell(202354),
stopcasting = Spell(291944),
 GaurdianAffinity = Spell(197491),
lustAT = Spell(155145),
lust1 = Spell(57724),
lust2 = Spell(57723),
lust3 = Spell(80354),
lust4 = Spell(95809),
lust5 = Spell(264689),
IncapacitatingRoar = Spell(99),
incapacitatingroar = Spell(22568), --ferocious bite

EclipseLunar = Spell(48518),
EclipseSolar = Spell(48517),

}

-- Spells
RubimRH.Spell[66] = {
    BlessingofFreedom = Spell(1044),
    BlindingLight = Spell(115750),
    SenseUndead = Spell(5502),
CleanseToxins = Spell(213644),
    autoattack = Spell(291944), -- regeneratin
    wristsx = Spell(255647), -- lights judgmenet
    tempestofthelightbringer = Spell(383396),

    DivineSteedBuff          = Spell(221883),
    BlessingofProtection     = Spell(1022),
    Forbearance              = Spell(25771),
    -- Racials
    AncestralCall            = Spell(274738),
    ArcanePulse              = Spell(260364),
    ArcaneTorrent            = Spell(155145),
    BagofTricks              = Spell(312411),
    Berserking               = Spell(26297),
    BloodFury                = Spell(20572),
    -- Fireblood                             = Spell(265221),
    GiftoftheNaaru           = Spell(59542),
    -- LightsJudgment                        = Spell(255647),
    -- Abilities
    Consecration             = Spell(26573),
    CrusaderStrike           = Spell(35395),
    DivineShield             = Spell(642),
    DivineSteed              = Spell(190784),
    FlashofLight             = Spell(19750),
    HammerofJustice          = Spell(853),
    HandofReckoning          = Spell(62124),
    Rebuke                   = Spell(96231),
    ShieldoftheRighteous     = Spell(53600),
    WordofGlory              = Spell(85673),
    -- Talents
    AvengingWrath            = Spell(31884),
    HammerofWrath            = Spell(24275),
    HolyAvenger              = Spell(105809),
    HolyAvengerBuff          = Spell(105809),
    LayonHands               = Spell(633),
    Seraphim                 = Spell(152262),
    SeraphimBuff             = Spell(152262),
    -- Covenants (Shadowlands)
    AshenHallow              = Spell(316958),
    BlessingofAutumn         = Spell(328622),
    BlessingofSpring         = Spell(328282),
    BlessingofSummer         = Spell(328620),
    BlessingofWinter         = Spell(328281),
    DivinePurpose            = Spell(223817),
    -- DivineTollCov                         = Spell(304971),
    DoorofShadows            = Spell(300728),
    Fleshcraft               = Spell(324631),
    Soulshape                = Spell(310143),
    SummonSteward            = Spell(324739),
    VanquishersHammer        = Spell(328204),
    VanquishersHammerBuff    = Spell(328204),
    -- Soulbinds/Conduits (Shadowlands)
    Expurgation              = Spell(339371),
    PustuleEruption          = Spell(351094),
    VengefulShock            = Spell(340006),
    VengefulShockDebuff      = Spell(340007),
    VolatileSolvent          = Spell(323074),
    VolatileSolventHumanBuff = Spell(323491),
    -- Auras
    ConcentrationAura        = Spell(317920),
    CrusaderAura             = Spell(32223),
    DevotionAura             = Spell(465),
    RetributionAura          = Spell(183435),
    -- Buffs
    Intercession             = Spell(391054),
    intercession           = Spell(105809),
    trinket                  = Spell(59547), -- gift of narru

    AvengingWrathBuff           = Spell(31884),
    ConsecrationBuff            = Spell(188370),
    DivinePurposeBuff           = Spell(223819),
    ScarsofFraternalStrifeBuff4 = Spell(368638),
    ShieldoftheRighteousBuff    = Spell(132403),
    TemptationBuff              = Spell(234143),
    -- Debuffs
    ConsecrationDebuff          = Spell(204242),
    CruelGarroteDebuff          = Spell(230011),
    -- Legendary Effects
    DivineResonanceBuff         = Spell(355455),
    FinalVerdictBuff            = Spell(337228),
    -- Pool


    -- Pool                                  = Spell(999910),
    Pool = Spell(397799),


    lust1 = Spell(57724),
    lust2 = Spell(57723),
    lust3 = Spell(80354),
    lust4 = Spell(95809),
    lust5 = Spell(264689),
    lustAT                   = Spell(20549), -- war stomp

    EyeofTyr = Spell(387174),
   

    ArdentDefender             = Spell(31850),
    ArdentDefenderBuff         = Spell(31850),
    AvengersShield             = Spell(31935),
    GuardianofAncientKings     = Spell(86659),

    HammeroftheRighteous       = Spell(53595),
    Judgment                   = Spell(275779),
    JudgmentDebuff             = Spell(197277),
    ShiningLight       = Spell(327510),
    -- Talents
    BlessedHammer              = Spell(204019),
    CrusadersJudgment          = Spell(204023),
    MomentofGlory              = Spell(327193),
    SanctifiedWrath            = Spell(171648),
    DivineToll                 = Spell(375576),



BastionofLight = Spell(378974),

}



RubimRH.Spell[268] = {
    -- Spells
		Vivify = Spell(116670),

    ArcaneTorrent = Spell(50613),
    Berserking = Spell(26297),
    BlackoutCombo = Spell(196736),
    BlackoutComboBuff = Spell(228563),
    BlackoutStrike = Spell(205523),
    BlackOxBrew = Spell(115399),
    BloodFury = Spell(20572),
    BreathOfFire = Spell(115181),
    BreathofFireDotDebuff = Spell(123725),
    Brews = Spell(115308),
    ChiBurst = Spell(123986),
    ChiWave = Spell(115098),
    DampenHarm = Spell(122278),
    DampenHarmBuff = Spell(122278),
    ExpelHarm = Spell(115072),
    ExplodingKeg = Spell(214326),
    FortifyingBrew = Spell(115203),
    FortifyingBrewBuff = Spell(115203),
    InvokeNiuzaotheBlackOx = Spell(132578),
    IronskinBrew = Spell(115308),
    IronskinBrewBuff = Spell(215479),
    KegSmash = Spell(121253),
    LightBrewing = Spell(196721),
    PotentKick = Spell(213047),
    PurifyingBrew = Spell(119582),
    RushingJadeWind = Spell(116847),
    TigerPalm = Spell(100780),
    HeavyStagger = Spell(124273),
    ModerateStagger = Spell(124274),
    LightStagger = Spell(124275),
    SpearHandStrike = Spell(116705),
    ModerateStagger = Spell(124274),
    HeavyStagger = Spell(124273),
    HealingElixir = Spell(122281),
    BlackOxStatue = Spell(115315),
    Guard = Spell(202162),
    LegSweep = Spell(119381),
	QuackingPalm = Spell(107079),
	Paralysis = Spell(115078),
	Vivify = Spell(116670),
	
	--8.2 Essences
  UnleashHeartOfAzeroth = Spell(280431),
  BloodOfTheEnemy       = Spell(297108),
  BloodOfTheEnemy2      = Spell(298273),
  BloodOfTheEnemy3      = Spell(298277),
  ConcentratedFlame     = Spell(295373),
  ConcentratedFlame2    = Spell(299349),
  ConcentratedFlame3    = Spell(299353),
  GuardianOfAzeroth     = Spell(295840),
  GuardianOfAzeroth2    = Spell(299355),
  GuardianOfAzeroth3    = Spell(299358),
  FocusedAzeriteBeam    = Spell(295258),
  FocusedAzeriteBeam2   = Spell(299336),
  FocusedAzeriteBeam3   = Spell(299338),
  PurifyingBlast        = Spell(295337),
  PurifyingBlast2       = Spell(299345),
  PurifyingBlast3       = Spell(299347),
  TheUnboundForce       = Spell(298452),
  TheUnboundForce2      = Spell(299376),
  TheUnboundForce3      = Spell(299378),
  RippleInSpace         = Spell(302731),
  RippleInSpace2        = Spell(302982),
  RippleInSpace3        = Spell(302983),
  WorldveinResonance    = Spell(295186),
  WorldveinResonance2   = Spell(298628),
  WorldveinResonance3   = Spell(299334),
  MemoryOfLucidDreams   = Spell(298357),
  MemoryOfLucidDreams2  = Spell(299372),
  MemoryOfLucidDreams3  = Spell(299374),
}


--Retribution
RubimRH.Spell[70] = {
BlessingofProtection = Spell(1022),
BlessingofFreedom = Spell(1044),
HammerofJustice = Spell(853),
hammerofjustice = Spell(20594),
DivineShield = Spell(642),
ArcaneTorrent = Spell(155145),
WakeofAshes = Spell(255937),
HandofHindrance = Spell(183218),
FlashofLight = Spell(19750),
KingsB = Spell(203538),
Kings = Spell(265221),
WisdomB = Spell(203539),
Wisdom = Spell(255647),
RecklessForce = Spell(298445),
trinket = Spell(20549),
HoJ = Spell(20594),
HS = Spell(291944),
FAB = Spell(299338),
FABg = Spell(84963),
BladeofJustice = Spell(184575),
Consecration = Spell(205228),
CrusaderStrike = Spell(35395),
DivineJudgment = Spell(271580),
DivineHammer = Spell(198034),
DivinePurpose = Spell(223817),
DivinePurposeBuff = Spell(223819),
DivineStorm = Spell(53385),
ExecutionSentence = Spell(343527),
GreaterJudgment = Spell(218718),
HolyWrath = Spell(210220),
Judgment = Spell(20271),
JudgmentDeBuff = Spell(197277),
JusticarsVengeance = Spell(215661),
TemplarsVerdict = Spell(85256),
TheFiresofJustice = Spell(203316),
TheFiresofJusticeBuff = Spell(209785),
Zeal = Spell(217020),
FinalVerdict = Spell(198038),
ShieldofVengeance = Spell(184662),
Forbearance = Spell(25771),
AvengingWrath = Spell(31884),
Crusade = Spell(231895),
Inquisition = Spell(84963),
DivineJudgement = Spell(271580),
HammerofWrath = Spell(24275),
RighteousVerdict = Spell(267610),
EmpyreanPowerAzerite = Spell(286390),
EmpyreanPowerBuffAzerite = Spell(286393),
DivineStormBuffAzerite = Spell(278523),
DivineRight = Spell(277678),
SelfLessHealerBuff = Spell(114250),
LayonHands = Spell(633),
WordofGlory = Spell(210191),
Rebuke = Spell(96231),
DivineSteed = Spell(190784),
LiadrinsFuryUnleashed = Spell(208408),
ScarletInquisitorsExpurgation = Spell(248289),
WhisperoftheNathrezim = Spell(207635),
HammerOfReckoning = Spell(247675),
HammerOfReckoningBuff = Spell(247677),
HandOfHidrance = Spell(183218),
CondensedLifeForce = Spell(299358),
UnleashHeartOfAzeroth = Spell(280431),
BloodOfTheEnemy = Spell(297108),
BloodOfTheEnemy2 = Spell(298273),
BloodOfTheEnemy3 = Spell(298277),
ConcentratedFlame = Spell(295373),
ConcentratedFlame2 = Spell(299349),
ConcentratedFlame3 = Spell(299353),
GuardianOfAzeroth = Spell(295840),
GuardianOfAzeroth2 = Spell(299355),
GuardianOfAzeroth3 = Spell(299358),
FocusedAzeriteBeam = Spell(295258),
FocusedAzeriteBeam2 = Spell(299336),
FocusedAzeriteBeam3 = Spell(299338),
PurifyingBlast = Spell(295337),
PurifyingBlast2 = Spell(299345),
PurifyingBlast3 = Spell(299347),
TheUnboundForce = Spell(298452),
TheUnboundForce2 = Spell(299376),
TheUnboundForce3 = Spell(299378),
RippleInSpace = Spell(302731),
RippleInSpace2 = Spell(302982),
RippleInSpace3 = Spell(302983),
WorldveinResonance = Spell(295186),
WorldveinResonance2 = Spell(298628),
WorldveinResonance3 = Spell(299334),
MemoryOfLucidDreams = Spell(298357),
MemoryOfLucidDreams2 = Spell(299372),
MemoryOfLucidDreams3 = Spell(299374),
}

RubimRH.Spell[251] = {
  -- Racials
  RaiseAlly = Spell(61999),
	  healthstone = Spell(291944), --regeneratin
  healingpot = Spell(176108), --potion in ggl
	  	lust1 = Spell(57724),
	lust2 = Spell(57723),
	lust3 = Spell(80354),
	lust4 = Spell(95809),
	lust5 = Spell(264689),
	lustAT = Spell(265221), -- fireblood

    ArcaneTorrent = Spell(50613),
    Berserking = Spell(26297),
    BloodFury = Spell(20572),
    GiftoftheNaaru = Spell(59547),

    -- Utility
    ControlUndead = Spell(45524),
    DeathGrip = Spell(49576),
    MindFreeze = Spell(47528),
    PathOfFrost = Spell(3714),
    WraithWalk = Spell(212552),
    ChillStreak = Spell(204160),

    -- Defensive
    AntiMagicShell = Spell(48707),
    DeathStrike = Spell(49998),
    IceboundFortitude = Spell(48792),
    DarkSuccor = Spell(101568),
    DeathGrip = Spell(49576),
    DeathsAdvance = Spell(48265),
    DeathPact = Spell(48743),

    -- Everything
    BreathofSindragosaBuff                = Spell(152279),
    RemorselessWinter                     = Spell(196770),
	RemorselessWinterz                    = Spell(179057),
    GatheringStorm                        = Spell(194912),
    GlacialAdvance                        = Spell(194913),
    Frostscythe                           = Spell(207230),
    FrostStrike                           = Spell(49143),
	FrostStrikez                         = Spell(162243),
	Frostscythez                          = Spell(211881),
    HowlingBlast                          = Spell(49184),
	HowlingBlastz                         = Spell(162794),
    RimeBuff                              = Spell(59052),
    KillingMachineBuff                    = Spell(51124),
    RunicAttenuation                      = Spell(207104),
    Obliterate                            = Spell(49020),
	Obliteratez                           = Spell(198013),
    HornofWinter                          = Spell(57330),
    ArcaneTorrent                         = Spell(50613),
    PillarofFrost                         = Spell(51271),
    ChainsofIce                           = Spell(45524),
	ChainsofIcez                          = Spell(188499),
    ColdHeartBuff                         = Spell(281209),
    PillarofFrostBuff                     = Spell(51271),
    FrostwyrmsFury                        = Spell(279302),
    EmpowerRuneWeaponBuff                 = Spell(47568),
    BloodFury                             = Spell(20572),
    Berserking                            = Spell(26297),
    EmpowerRuneWeapon                     = Spell(47568),
    BreathofSindragosa                    = Spell(152279),
    ColdHeart                             = Spell(281208),
    RazoriceDebuff                        = Spell(51714),
    FrozenPulseBuff                       = Spell(194909),
    FrozenPulse                           = Spell(194909),
    FrostFeverDebuff                      = Spell(55095),
    IcyTalonsBuff                         = Spell(194879),
    Obliteration                          = Spell(281238),
    DeathStrike                           = Spell(49998),
    DeathStrikeBuff                       = Spell(101568),
    FrozenTempest                         = Spell(278487),
    UnholyStrengthBuff                    = Spell(53365),
    
Lichborne = Spell(49039),

    -- PVP

    Transfusion = Spell(288977),
	
	-- Azerite
	IcyCitadel                            = Spell(272718),
    IcyCitadelBuff                        = Spell(272719),
	
	  --8.2 Essences
  UnleashHeartOfAzeroth = Spell(280431),
  BloodOfTheEnemy       = Spell(297108),
  BloodOfTheEnemy2      = Spell(298273),
  BloodOfTheEnemy3      = Spell(298277),
  ConcentratedFlameDebuff= Spell(295368),
  ConcentratedFlame     = Spell(295373),
  ConcentratedFlame2    = Spell(299349),
  ConcentratedFlame3    = Spell(299353),
  GuardianOfAzeroth     = Spell(295840),
  GuardianOfAzeroth2    = Spell(299355),
  GuardianOfAzeroth3    = Spell(299358),
  FocusedAzeriteBeam    = Spell(295258),
  FocusedAzeriteBeam2   = Spell(299336),
  FocusedAzeriteBeam3   = Spell(299338),
  PurifyingBlast        = Spell(295337),
  PurifyingBlast2       = Spell(299345),
  PurifyingBlast3       = Spell(299347),
  RecklessForceBuff     = Spell(302932),
  TheUnboundForce       = Spell(298452),
  TheUnboundForce2      = Spell(299376),
  TheUnboundForce3      = Spell(299378),
  RippleInSpace         = Spell(302731),
  RippleInSpace2        = Spell(302982),
  RippleInSpace3        = Spell(302983),
  WorldveinResonance    = Spell(295186),
  WorldveinResonance2   = Spell(298628),
  WorldveinResonance3   = Spell(299334),
  MemoryOfLucidDreams   = Spell(298357),
  MemoryOfLucidDreams2  = Spell(299372),
  MemoryOfLucidDreams3  = Spell(299374),
  RecklessForceCounter  = Spell(298409),
  RecklessForceCounter2 = Spell(302917)
  }

RubimRH.Spell[73] = {
    -- Racials
	RallyingCry = Spell(97462),
    BattleShout = Spell(6673),
    ArcaneTorrent = Spell(69179),
    Berserking = Spell(26297),
	Reflect = Spell(23920),
	ShieldBlockBuff = Spell(132404),
    Shadowmeld = Spell(58984),
    -- Abilities
	CracklingThunder = Spell(203201),
    Ravager = Spell(22401),
    BattleCry = Spell(1719),
	StormBolt = Spell(107570),
    BerserkerRage = Spell(18499),
    Charge = Spell(100),
    DemoralizingShout = Spell(1160),
    Devastate = Spell(20243),
    FuriousSlash = Spell(100130),
    HeroicLeap = Spell(6544),
    HeroicThrow = Spell(57755),
    Revenge = Spell(6572),
    RevengeBuff = Spell(5302),
    ShieldSlam = Spell(23922),
    ThunderClap = Spell(6343),
    VictoryRush = Spell(34428),
    Victorious = Spell(32216),
	DragonRoar = Spell (23260),
    -- Talents
	BoomingVoice = Spell(202743),
	ShieldBash = Spell(35178),
	Bolster = Spell(280001),
    ImpendingVictory = Spell(202168),
    ImpendingVictoryProc = Spell(32216),
    Shockwave = Spell(46968),
    Vengeance = Spell(202572),
    VengeanceIP = Spell(202574),
    VengeanceRV = Spell(202573),
	Execute = Spell(163201), 
	UnstoppableForce = Spell(275336),
    -- Artifact
    NeltharionsFury = Spell(203524),
    -- Defensive
    IgnorePain = Spell(190456),
    LastStand = Spell(12975),
    Pummel = Spell(6552),
    ShieldBlock = Spell(2565),
    ShieldBlockB = Spell(132404),
    Avatar = Spell(107574),
	ShieldWall = Spell(871),
	FM = Spell(20594),
    Condemn = Spell(317349),
    trinket = Spell(155145),
    IntimidatingShout = Spell(5246),
}

RubimRH.Spell[260] = {
    Shiv = Spell(5938),

BladeRush = Spell(271877),

stopcasting = Spell(291944), -- regeneratin

 
CripplingPoison = Spell(3408),
cripplingpoison = Spell(260364), -- arcane pulse
InstantPoison = Spell(315584),
instantpoison = Spell(274738), --ancestral call
 

lust1 = Spell(57724),
lust2 = Spell(57723),
lust3 = Spell(80354),
lust4 = Spell(95809),
lust5 = Spell(264689),
--enrage
UndyingRage = Spell(333227),

		  --8.2 Essences
  CondensedLifeForce = Spell(299358),
  UnleashHeartOfAzeroth = Spell(280431),
  BloodOfTheEnemy       = Spell(297108),
  BloodOfTheEnemy2      = Spell(298273),
  BloodOfTheEnemy3      = Spell(298277),
  ConcentratedFlame     = Spell(295373),
  ConcentratedFlame2    = Spell(299349),
  ConcentratedFlame3    = Spell(299353),
  GuardianOfAzeroth     = Spell(295840),
  GuardianOfAzeroth2    = Spell(299355),
  GuardianOfAzeroth3    = Spell(299358),
  FocusedAzeriteBeam    = Spell(295258),
  FocusedAzeriteBeam2   = Spell(299336),
  FocusedAzeriteBeam3   = Spell(299338),
  PurifyingBlast        = Spell(295337),
  PurifyingBlast2       = Spell(299345),
  PurifyingBlast3       = Spell(299347),
  TheUnboundForce       = Spell(298452),
  TheUnboundForce2      = Spell(299376),
  TheUnboundForce3      = Spell(299378),
  RippleInSpace         = Spell(302731),
  RippleInSpace2        = Spell(302982),
  RippleInSpace3        = Spell(302983),
  WorldveinResonance    = Spell(295186),
  WorldveinResonance2   = Spell(298628),
  WorldveinResonance3   = Spell(299334),
  MemoryOfLucidDreams   = Spell(298357),
  MemoryOfLucidDreams2  = Spell(299372),
  MemoryOfLucidDreams3  = Spell(299374),
  trink2 = Spell(59547), -- gift of naaru
	  ConcentratedFlamedebuff     = Spell(295368),
	FocusedAzeriteBeam = Spell(295258),
	KYWAY = Spell(288979),
	
    AceUpYourSleeve = Spell(278676),
    Deadshot = Spell(272935),
    Berserking = Spell(26297),

    Darkflight = Spell(68992),

    -- Debuff List
	Distract = Spell(1725),
	distract = Spell(20572), --shadowmeld
lustAT = Spell(155145),

bagoftricks = Spell(312411),
    	--Mount
    WaterStrider = Spell(118089),
    BugMount = Spell(243795),
razorcoral = Spell(303568),
ConductiveInk = Spell(302565),
    -- Abilities
    AdrenalineRush = Spell(13750),
    Ambush = Spell(8676),
    Detection = Spell(56814), --opener
	KidneyShot = Spell(408),
    BetweentheEyes = Spell(315341),
    BladeFlurry = Spell(13877),
    BladeFlurry2 = Spell(103828), -- Icon: Prot. Warrior Warbringer
    DeeperStratagem = Spell(193531),
    DeviousStratagem = Spell(394321),
    Opportunity = Spell(195627),
    PistolShot = Spell(185763),
    RolltheBones = Spell(315508),
    Dispatch = Spell(2098),
    SinisterStrike = Spell(193315),
	Dreadblades = Spell(343142),
    Stealth = Spell(1784),
    Vanish = Spell(1856),
    VanishBuff = Spell(11327),
    Shivv = Spell(248744),
    Riposte = Spell(199754),
    WilloftheForsaken = Spell(7744),
    CloakofShadows = Spell(31224),
    -- Talents
	trink = Spell(265221),
    Alacrity = Spell(193539),
    AlacrityBuff = Spell(193538),
    Anticipation = Spell(114015),
    CannonballBarrage = Spell(185767),
    DeathfromAbove = Spell(152150),
    DeeperStratagem = Spell(193531),
    DirtyTricks = Spell(108216),
    GhostlyStrike = Spell(196937),
    KillingSpree = Spell(51690),
    MarkedforDeath = Spell(137619),
    QuickDraw = Spell(196938),
    Tricks = Spell(57934),
    ToTT = Spell(58984),
	sliceanddice = Spell(198529), -- plunder armor
    SliceandDice = Spell(315496),
    Vigor = Spell(14983),
    -- Artifact
	Exhaustion = Spell(57723),
	Blind = Spell(2094),
    Blunderbuss = Spell(202895),
    CurseoftheDreadblades = Spell(202665),
    HiddenBlade = Spell(202754),
    LoadedDice = Spell(256171),
    DeadshotBuff = Spell(272940),
	AceUpYourSleeve = Spell(278676),
	SnakeEyes = Spell(275846),
	SnakeEyesBuff = Spell(275863),
    -- Defensive
	DS = Spell(642),
	CheapShot = Spell(1833),
	Dismantle= Spell(207777),
    CrimsonVial = Spell(185311),
    Feint = Spell(1966),
    -- Utility
    Gouge = Spell(1776),
    Kick = Spell(1766),
    Sprint = Spell(2983),
    -- Roll the Bones
    Broadside = Spell(193356),
    BuriedTreasure = Spell(199600),
    GrandMelee = Spell(193358),
    SkullandCrossbones = Spell(199603),
	GCBoon = Spell(20572),
    RuthlessPrecision = Spell(193357),
    TrueBearing = Spell(193359),


}

RubimRH.Spell[269] = {
RingofPeace = Spell(116844),
LegSweep = Spell(119381),
FlyingSerpentKick = Spell(101545),
Paralysis = Spell(115078),
CracklingJadeLightning = Spell(117952),
}

RubimRH.Spell[270] = {
Vivify = Spell(116670),
FaelineStomp = Spell(388193),
LegSweep = Spell(119381),
LifeCocoon = Spell(116849),
ChiJi = Spell(325197),
RingofPeace = Spell(116844),
Revival = Spell(115310),
Detox = Spell(115450),
}
----SHAMMY
--ELE
RubimRH.Spell[262] = {
    -- Racials
    Berserking = Spell(26297),
    BloodFury = Spell(33697),
    -- Abilities
    FlameShock = Spell(188389),
    FlameShockDebuff = Spell(188389),
    BloodLust = Spell(2825),
    --BloodLustBuff = Spell(2825),

    TotemMastery = Spell(210643),
    EmberTotemBuff = Spell(210658),
    TailwindTotemBuff = Spell(210659),
    ResonanceTotemBuff = Spell(202192),
    StormTotemBuff = Spell(210652),

    HealingSurge = Spell(188070),

    EarthShock = Spell(8042),
    LavaBurst = Spell(51505),
    FireElemental = Spell(198067),
    LightningBolt = Spell(188196),
    LavaBeam = Spell(114074),
    EarthQuake = Spell(61882),
    LavaSurgeBuff = Spell(77762),
    ChainLightning = Spell(188443),
    ElementalFocusBuff = Spell(16246),
    FrostShock = Spell(196840),

    -- Talents
    ElementalMastery = Spell(16166),
    ElementalMasteryBuff = Spell(16166),
    Ascendance = Spell(114050),
    AscendanceBuff = Spell(114050),
    LightningRod = Spell(210689),
    LightningRodDebuff = Spell(197209),
    LiquidMagmaTotem = Spell(192222),
    ElementalBlast = Spell(117014),
    Aftershock = Spell(210707),
    Icefury = Spell(210714),
    IcefuryBuff = Spell(210714),

    -- Artifact
    Stormkeeper = Spell(205495),
    StormkeeperBuff = Spell(205495),
    SwellingMaelstrom = Spell(238105),
    PowerOfTheMaelstrom = Spell(191861),
    PowerOfTheMaelstromBuff = Spell(191861),

    -- Tier bonus
    EarthenStrengthBuff = Spell(252141),

    -- Utility
    WindShear = Spell(57994),
}

----ROGUE
--ASS

--SUB
RubimRH.Spell[261] = {
    -- Racials
    brez = Spell(69070), --rocket jump
	Rupture = Spell(1943),
    ArcanePulse = Spell(260364),
    ArcaneTorrent = Spell(50613),
    Berserking = Spell(26297),
    BloodFury = Spell(20572),
    Shadowmeld = Spell(58984),
    -- Abilities
    Backstab = Spell(53),
	ShurikenTornado = Spell(277925),
    Eviscerate = Spell(196819),
    Nightblade = Spell(195452),
    ShadowBlades = Spell(121471),
    ShurikenComboBuff = Spell(245640),
    ShadowDance = Spell(185313),
    ShadowDanceBuff = Spell(185422),
    Shadowstrike = Spell(185438),
    ShurikenStorm = Spell(197835),
    ShurikenToss = Spell(114014),
    Stealth = Spell(1784),
    Stealth2 = Spell(115191), -- w/ Subterfuge Talent
    SymbolsofDeath = Spell(212283),
    Vanish = Spell(1856),
    VanishBuff = Spell(11327),
    VanishBuff2 = Spell(115193), -- w/ Subterfuge Talent
    -- Talents
    Alacrity = Spell(193539),
    DarkShadow = Spell(245687),
    DeeperStratagem = Spell(193531),
    EnvelopingShadows = Spell(238104),
    FindWeaknessDebuff = Spell(91021),
    Gloomblade = Spell(200758),
    MarkedforDeath = Spell(137619),
    MasterofShadows = Spell(196976),
    Nightstalker = Spell(14062),
    SecretTechnique = Spell(280719),
    ShadowFocus = Spell(108209),
    ShurikenTornado = Spell(277925),
    Subterfuge = Spell(108208),
    Vigor = Spell(14983),
    -- Azerite Traits
    SharpenedBladesBuff = Spell(272916),
    -- Defensive
    CrimsonVial = Spell(185311),
    Feint = Spell(1966),
    -- Utility
    Blind = Spell(2094),
    CheapShot = Spell(1833),
    Kick = Spell(1766),
    KidneyShot = Spell(408),
    Sprint = Spell(2983),
    -- Misc
}

----HUNTER
--BeastMastery

----DRUID
-- Feral
RubimRH.Spell[103] = {
    Regrowth = Spell(8936),
	Soothe = Spell(2908),
    Hibernate = Spell(2637),
    RemoveCorruption = Spell(2782),
	WildCharge = Spell(49376),
	Typhoon = Spell(132469),
	Typhoonz = Spell(20549), --war stomp
	Vortex = Spell(102793),
    Convoke = Spell(391528),
    Bloodtalons = Spell(155672),
    StampedingRoar = Spell(77764),
    CatForm = Spell(768),
	IncapacitatingRoar = Spell(99),
    BearForm = Spell(5487),
    Prowl = Spell(5215),
    Rebirth = Spell(20484),
    IncarnationBuff = Spell(102543),
    JungleStalkerBuff = Spell(252071),
	Maim = Spell(22570),
    Berserk = Spell(106951),
    TigersFury = Spell(5217),
    TigersFuryBuff = Spell(5217),
    EntanglingRoots = Spell(339),
    Berserking = Spell(26297),
    FeralFrenzy = Spell(274837),
    Incarnation = Spell(102543),
    BerserkBuff = Spell(106951),
    Shadowmeld = Spell(58984),
    Rake = Spell(1822),
    RakeDebuff = Spell(155722),
    BloodtalonsBuff = Spell(145152),
    CatFormBuff = Spell(768),
    ProwlBuff = Spell(5215),
    ShadowmeldBuff = Spell(58984),
    FerociousBite = Spell(22568),
    RipDebuff = Spell(1079),
    Sabertooth = Spell(202031),
    PredatorySwiftnessBuff = Spell(69369),
    ApexPredatorBuff = Spell(252752),
    MomentofClarity = Spell(236068),
    SavageRoar = Spell(52610),
    SavageRoarBuff = Spell(52610),
    Rip = Spell(1079),
    FerociousBiteMaxEnergy = Spell(22568),
    BrutalSlash = Spell(202028),
    ThrashCat = Spell(106830),
    ThrashCatDebuff = Spell(106830),
    MoonfireCat = Spell(155625),
    MoonfireCatDebuff = Spell(155625),
    ClearcastingBuff = Spell(135700),
    SwipeCat = Spell(106785),
    Shred = Spell(5221),
    LunarInspiration = Spell(155580),
	Dash = Spell(1850),
	FrenziedRegeneration = Spell(22842),
}
-- Guardian
RubimRH.Spell[104] = {
Quake = Spell(240447),
MarkOfTheWild = Spell(1126),
MassEntanglement = Spell(102359),
forceofnature = Spell(205636),
Vortex = Spell(102793),
vortex = Spell(58984),
FrenziedRegeneration = Spell(22842),
Thrash = Spell(20549), --warstomp
ThrashDebuff = Spell(192090),
Mangle = Spell(33917),
Ironfur = Spell(192081),
StarfallBuff = Spell(191034),
TravelForm = Spell(783),
BearForm = Spell(5487),
CatForm = Spell(768),
Rebirth = Spell(20484),
EntanglingRoots = Spell(339),
Cyclone = Spell(33786),
cyclone = Spell(287712),
swiftmend = Spell(18562),
typhoon = Spell(209749),
Rejuvenation = Spell(774),
WildGrowth = Spell(48438),
RemoveCorruption = Spell(2782),
Dash = Spell(1850),
StampedingRoar = Spell(106898),

    Pull                             	    = Spell(8921),	
    Gore                                    = Spell(210706),
    GoreBuff                                = Spell(93622),
    GoryFur                                 = Spell(201671),
    Mangle                                  = Spell(33917),
    Maul                                    = Spell(6807),
    Moonfire                                = Spell(8921),
    MoonfireDebuff                          = Spell(164812),
    Sunfire                                 = Spell(197630),
    SunfireDebuff                           = Spell(164815),
    Starsurge                               = Spell(197626),
    LunarEmpowerment                        = Spell(164547),
    SolarEmpowerment                        = Spell(164545),
    LunarStrike                             = Spell(197628),
    Wrath                                   = Spell(197629),
    Regrowth                                = Spell(8936),
    Swipe                                   = Spell(213771),
    Thrash                                  = Spell(77758),
    ThrashDebuff                            = Spell(192090),
    ThrashCat                               = Spell(106830),
	ThrashBearDebuff                        = Spell(192090),
    Prowl                                   = Spell(5215),
	LayeredMane                           = Spell(279552),
    -- Talents
    BalanceAffinity                         = Spell(197488),
    BloodFrenzy                             = Spell(203962),
    Brambles                                = Spell(203953),
    BristlingFur                            = Spell(155835),
    Earthwarden                             = Spell(203974),
    EarthwardenBuff                         = Spell(203975),
    FeralAffinity                           = Spell(202155),
    GalacticGuardian                        = Spell(203964),
    GalacticGuardianBuff                    = Spell(213708),
    GuardianOfElune                         = Spell(155578),
    GuardianOfEluneBuff                     = Spell(213680),
    Incarnation                             = Spell(102558),
    LunarBeam                               = Spell(204066),
    Pulverize                               = Spell(80313),
    PulverizeBuff                           = Spell(158792),
    RestorationAffinity                     = Spell(197492),
    SouloftheForest                         = Spell(158477),
    MightyBash                              = Spell(5211),
    Typhoon                                 = Spell(132469),
    Entanglement                            = Spell(102359),
	IncarnationBuff                       = Spell(102558),
    -- Artifact
    RageoftheSleeper                        = Spell(200851),
    -- Defensive
    SurvivalInstincts                       = Spell(61336),
    Barkskin                                = Spell(22812),
    -- Utility
    Growl                                   = Spell(6795),
    SkullBash                               = Spell(106839),
	RemoveCorruption                        = Spell(2782),
	IncapacitatingRoar                      = Spell(99),
    -- Affinity
    FerociousBite                           = Spell(22568),
    HealingTouch                            = Spell(5185),
    Rake                                    = Spell(1822),
    RakeDebuff                              = Spell(155722),
    Rejuvenation                            = Spell(774),
    Rip                                     = Spell(1079),
    Shred                                   = Spell(5221),
    Swiftmend                               = Spell(18562),
	WildChargeTalent                      = Spell(102401),
    WildChargeBear                        = Spell(16979),
    -- Shapeshift
    BearForm                                = Spell(5487),
    CatForm                                 = Spell(768),
    MoonkinForm                             = Spell(197625),
    TravelForm                              = Spell(783),
	HeartEssence                            = Spell(298554),
    SharpenedClawsBuff                      = Spell(279943),
	--8.2 Essences
    UnleashHeartOfAzeroth                   = Spell(280431),
    BloodOfTheEnemy                         = Spell(297108),
    BloodOfTheEnemy2                        = Spell(298273),
    BloodOfTheEnemy3                        = Spell(298277),
    ConcentratedFlame                       = Spell(295373),
    ConcentratedFlame2                      = Spell(299349),
    ConcentratedFlame3                      = Spell(299353),
    GuardianOfAzeroth                       = Spell(295840),
    GuardianOfAzeroth2                      = Spell(299355),
    GuardianOfAzeroth3                      = Spell(299358),
    FocusedAzeriteBeam                      = Spell(295258),
    FocusedAzeriteBeam2                     = Spell(299336),
    FocusedAzeriteBeam3                     = Spell(299338),
    PurifyingBlast                          = Spell(295337),
    PurifyingBlast2                         = Spell(299345),
    PurifyingBlast3                         = Spell(299347),
    TheUnboundForce                         = Spell(298452),
    TheUnboundForce2                        = Spell(299376),
    TheUnboundForce3                        = Spell(299378),
    RippleInSpace                           = Spell(302731),
    RippleInSpace2                          = Spell(302982),
    RippleInSpace3                          = Spell(302983),
    WorldveinResonance                      = Spell(295186),
    WorldveinResonance2                     = Spell(298628),
    WorldveinResonance3                     = Spell(299334),
    MemoryOfLucidDreams                     = Spell(298357),
    MemoryOfLucidDreams2                    = Spell(299372),
    MemoryOfLucidDreams3                    = Spell(299374),
	Conflict1                               = Spell(303823),
	Conflict2                               = Spell(304088),
	Conflict3                               = Spell(304121),
}


----DEATH KNIGHT
--FROST

----DEMONHUNTER
RubimRH.Spell[581] = {
    -- Baseline
    SigilofSilence = Spell(207682),
}
-- Vengeance


-- Havoc
RubimRH.Spell[577] = {
    EyeBeam = Spell(198013),
	ChaosNova = Spell(179057),
	Metamorphosis = Spell(191427),
	FelRush = Spell(195072),
	VengefulRetreat = Spell(198793),
	FelEruption = Spell(211881),
	Darkness = Spell(196718),
	GlaiveTempest = Spell(342817),
    Blur = Spell(198589),
    ConsumeMagic = Spell(278326),
	Imprison = Spell(217832),
    SpectralSight = Spell(188501),
    ThrowGlaive = Spell(185123),
    SinfulBrand = Spell(317009),
	theHunt = Spell(323639),
}

-- Affliction
RubimRH.Spell[265] = {
    -- Baseline
    DemonicGateway = Spell(111771),
    CreateSoulwell = Spell(29893),
    EnslaveDemon = Spell(1098),
    UnendingResolve = Spell(104773),
    Soulstone = Spell(20707),
    RitualOfSummoning = Spell(698),
    CommandDemon = Spell(119898),
    SummonFelhunter = Spell(691),
    Banish = Spell(710),
    SummonSuccubus = Spell(712),
    UnendingBreath = Spell(5697),
    HealthFunnel = Spell(755),
    SummonVoidwalker = Spell(697),
    CreateHealthstone = Spell(6201),
    Fear = Spell(5782),
    SummonImp = Spell(688),
    -- Specialization
    PotentAfflictions = Spell(77215),
    Shadowfury = Spell(30283),
    SummonDarkglare = Spell(205180),
    Agony = Spell(980),
    SeedOfCorruption = Spell(27243),
    UnstableAffliction = Spell(30108),
    UnstableAfflictionDot = Spell(233490),
    DrainLife = Spell(234153),
    Corruption = Spell(172),
    CorruptionPerma = Spell(146739),
    ShadowBolt = Spell(232670),
    -- Talents
    CreepingDeath = Spell(264000),
    Deathbolt = Spell(264106),
    DarkSoulMisery = Spell(113860),
    SoulConduit = Spell(215941),
    GrimoireOfSacrifice = Spell(108503),
    Haunt = Spell(48181),
    PhantomSingularity = Spell(205179),
    SowTheSeeds = Spell(196226),
    VileTaint = Spell(278350),
    AbsoluteCorruption = Spell(196103),
    WritheInAgony = Spell(196102),
    DrainSoul = Spell(198590),
    Nightfall = Spell(108558),
    SiphonLife = Spell(63106)
}

RubimRH.Spell[266] = {
  -- Racials
  Berserking            = Spell(26297),
  BloodFury             = Spell(20572),
  Fireblood             = Spell(265221),
  -- Abilities
  DrainLife             = Spell(234153),
  SummonDemonicTyrant   = Spell(265187),
  SummonImp             = Spell(688),
  SummonFelguard        = Spell(30146),
  HandOfGuldan          = Spell(105174),
  ShadowBolt            = Spell(686),
  Demonbolt             = Spell(264178),
  CallDreadStalkers     = Spell(104316),
  Fear                  = Spell(5782),
  Implosion             = Spell(196277),
  Shadowfury            = Spell(30283),

  -- Pet abilities
  CauterizeMaster         = Spell(119905),--imp
  Suffering               = Spell(119907),--voidwalker
  Whiplash                = Spell(119909),--Bitch
  FelStormFake            = Spell(29893),-- HAck == CreateSoulwell
  FelStorm                = Spell(89751),--FelGuard
  PetStun                 = Spell(119914),
  SpellLock               = Spell(119898),

  -- Talents
  Dreadlash               = Spell(264078),
  DemonicStrength         = Spell(267171),
  BilescourgeBombers      = Spell(267211),

  DemonicCalling          = Spell(205145),
  PowerSiphon             = Spell(264130),
  Doom                    = Spell(265412),
  DoomDebuff              = Spell(265412),

  DemonSkin               = Spell(219272),
  BurningRush             = Spell(111400),
  DarkPact                = Spell(108416),

  FromTheShadows          = Spell(267170),
  SoulStrike              = Spell(264057),
  SummonVilefiend         = Spell(264119),

  Darkfury                = Spell(264874),
  MortalCoil              = Spell(6789),
  DemonicCircle           = Spell(268358),

  InnerDemons             = Spell(267216),
  SoulConduit             = Spell(215941),
  GrimoireFelguard        = Spell(111898),

  SacrificedSouls         = Spell(267214),
  DemonicConsumption      = Spell(267215),
  NetherPortal            = Spell(267217),
  NetherPortalBuff        = Spell(267218),

  -- Defensive
  UnendingResolve         = Spell(104773),

  -- Azerite
  ForbiddenKnowledge      = Spell(279666),
  BalefulInvocation       = Spell(287059),
  ExplosivePotentialBuff  = Spell(275398),
  ExplosivePotential      = Spell(275395),

  -- Utility
  TargetEnemy             = Spell(153911),--doesnt work
  CreateHealthstone       = Spell(6201),--using this instead to target enemy
  
  -- Misc
  DemonicCallingBuff      = Spell(205146),
  DemonicCoreBuff         = Spell(264173),
  DemonicPowerBuff        = Spell(265273)
}